# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.11.4
# Generation date: 2026-04-15
# ===================================================================

#' @title mosaic: Build a mosaic, either virtual (VRT) or materialized
#' @description
#' Build a mosaic, either virtual (VRT) or materialized.
#' 
#' See \url{https://gdal.org/en/3.11.4/programs/gdal_raster_mosaic.html} for detailed GDAL documentation.
#' @param input Input raster datasets (or specify a @<filename> to point to a file containing filenames). Format: `INPUTS`. `1` to `2147483647` value(s). Can also be a [gdal_job] object to extend a pipeline
#' @param output Output raster dataset (Dataset path) (required)
#' @param output_format Output format ("GDALG" allowed)
#' @param target_aligned_pixels Round target extent to target resolution (Logical)
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`
#' @param band Input band(s) (1-based index) (Integer vector)
#' @param overwrite Whether overwriting existing output is allowed (Logical) (Default: `false`)
#' @param resolution Target resolution (in destination CRS units). Format: `<xres>,<yres>|same|average|common|highest|lowest` (Default: `same`)
#' @param bbox Target bounding box as xmin,ymin,xmax,ymax (in destination CRS units). Exactly `4` value(s)
#' @param src_nodata Set nodata values for input bands.. `1` to `2147483647` value(s)
#' @param dst_nodata Set nodata values at the destination band level.. `1` to `2147483647` value(s)
#' @param hide_nodata Makes the destination band not report the NoData. (Logical)
#' @param add_alpha Adds an alpha mask band to the destination when the source raster have none. (Logical)
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples

#' job <- gdal_raster_mosaic(input = "doq/*.tif", output = "doq_index.vrt", 
#'     hide_nodata = TRUE, dst_nodata = "0,0,255")
#' \dontrun{
#'   result <- gdal_job_run(job)
#' }
#' @export
gdal_raster_mosaic <- function(input = NULL,
  output,
  output_format = NULL,
  target_aligned_pixels = FALSE,
  creation_option = NULL,
  band = NULL,
  overwrite = FALSE,
  resolution = NULL,
  bbox = NULL,
  src_nodata = NULL,
  dst_nodata = NULL,
  hide_nodata = FALSE,
  add_alpha = FALSE) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(target_aligned_pixels)) new_args[["target_aligned_pixels"]] <- target_aligned_pixels
  if (!missing(creation_option)) new_args[["creation_option"]] <- creation_option
  if (!missing(band)) new_args[["band"]] <- band
  if (!missing(overwrite)) new_args[["overwrite"]] <- overwrite
  if (!missing(resolution)) new_args[["resolution"]] <- resolution
  if (!missing(bbox)) new_args[["bbox"]] <- bbox
  if (!missing(src_nodata)) new_args[["src_nodata"]] <- src_nodata
  if (!missing(dst_nodata)) new_args[["dst_nodata"]] <- dst_nodata
  if (!missing(hide_nodata)) new_args[["hide_nodata"]] <- hide_nodata
  if (!missing(add_alpha)) new_args[["add_alpha"]] <- add_alpha

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("raster", "mosaic"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    input = list(min_count = 1, max_count = 2147483647),
    output = list(min_count = 0, max_count = 1),
    output_format = list(min_count = 0, max_count = 1),
    target_aligned_pixels = list(min_count = 0, max_count = 1),
    creation_option = list(min_count = 0, max_count = 2147483647),
    band = list(min_count = 0, max_count = 2147483647),
    overwrite = list(min_count = 0, max_count = 1),
    resolution = list(min_count = 0, max_count = 1),
    bbox = list(min_count = 4, max_count = 4),
    src_nodata = list(min_count = 1, max_count = 2147483647),
    dst_nodata = list(min_count = 1, max_count = 2147483647),
    hide_nodata = list(min_count = 0, max_count = 1),
    add_alpha = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("raster", "mosaic"), arguments = merged_args, arg_mapping = .arg_mapping)
}

