# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.11.4
# Generation date: 2026-04-15
# ===================================================================

#' @title clean-collar: Clean the collar of a raster dataset, removing noise
#' @description
#' Clean the collar of a raster dataset, removing noise.
#' 
#' See \url{https://gdal.org/en/3.11.4/programs/gdal_raster_clean-collar.html} for detailed GDAL documentation.
#' @param input Input raster dataset (Dataset path) (required). Can also be a [gdal_job] object to extend a pipeline
#' @param input_format Input formats (Character vector) (Advanced)
#' @param output Output raster dataset (Dataset path)
#' @param output_format Output format
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>` (Advanced)
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`
#' @param overwrite Whether overwriting existing output is allowed (Logical) (Default: `false`)
#' @param update Whether to open existing dataset in update mode (Logical) (Default: `false`)
#' @param color Transparent color(s): tuple of integer (like 'r,g,b'), 'black', 'white' (Character vector) (Default: `black`)
#' @param color_threshold Select how far from specified transparent colors the pixel values are considered transparent. (Integer) (Default: `15`). Minimum: `0`
#' @param pixel_distance Number of consecutive transparent pixels that can be encountered before the giving up search inwards. (Integer) (Default: `2`). Minimum: `0`
#' @param add_alpha Adds an alpha band to the output dataset. (Logical)
#' @param add_mask Adds a mask band to the output dataset. (Logical)
#' @param algorithm Algorithm to apply. Choices: "floodfill", "twopasses" (Default: `floodfill`)
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples

#' job <- gdal_raster_clean_collar(update = "my.tif")
#' \dontrun{
#'   result <- gdal_job_run(job)
#' }
#' @export
gdal_raster_clean_collar <- function(input,
  input_format = NULL,
  output = NULL,
  output_format = NULL,
  open_option = NULL,
  creation_option = NULL,
  overwrite = FALSE,
  update = FALSE,
  color = NULL,
  color_threshold = NULL,
  pixel_distance = NULL,
  add_alpha = FALSE,
  add_mask = FALSE,
  algorithm = NULL) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(input_format)) new_args[["input_format"]] <- input_format
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(creation_option)) new_args[["creation_option"]] <- creation_option
  if (!missing(overwrite)) new_args[["overwrite"]] <- overwrite
  if (!missing(update)) new_args[["update"]] <- update
  if (!missing(color)) new_args[["color"]] <- color
  if (!missing(color_threshold)) new_args[["color_threshold"]] <- color_threshold
  if (!missing(pixel_distance)) new_args[["pixel_distance"]] <- pixel_distance
  if (!missing(add_alpha)) new_args[["add_alpha"]] <- add_alpha
  if (!missing(add_mask)) new_args[["add_mask"]] <- add_mask
  if (!missing(algorithm)) new_args[["algorithm"]] <- algorithm

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("raster", "clean-collar"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    input = list(min_count = 0, max_count = 1),
    input_format = list(min_count = 0, max_count = 2147483647),
    output = list(min_count = 0, max_count = 1),
    output_format = list(min_count = 0, max_count = 1),
    open_option = list(min_count = 0, max_count = 2147483647),
    creation_option = list(min_count = 0, max_count = 2147483647),
    overwrite = list(min_count = 0, max_count = 1),
    update = list(min_count = 0, max_count = 1),
    color = list(min_count = 0, max_count = 2147483647),
    color_threshold = list(min_count = 0, max_count = 1),
    pixel_distance = list(min_count = 0, max_count = 1),
    add_alpha = list(min_count = 0, max_count = 1),
    add_mask = list(min_count = 0, max_count = 1),
    algorithm = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("raster", "clean-collar"), arguments = merged_args, arg_mapping = .arg_mapping)
}

