# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.11.4
# Generation date: 2026-04-15
# ===================================================================

#' @title pixel-info: Return information on a pixel of a raster dataset
#' @description
#' Return information on a pixel of a raster dataset.
#' 
#' See \url{https://gdal.org/en/3.11.4/programs/gdal_raster_pixel-info.html} for detailed GDAL documentation.
#' @param input Input raster dataset (Dataset path) (required). Can also be a [gdal_job] object to extend a pipeline
#' @param input_format Input formats (Character vector) (Advanced)
#' @param output_format Output format. Choices: "geojson", "csv" (Default: `geojson`)
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>` (Advanced)
#' @param band Input band(s) (1-based index) (Integer vector)
#' @param overview Which overview level of source file must be used (Integer). Minimum: `0`
#' @param position Pixel position. Format: `<column,line> or <X,Y>`
#' @param position_crs CRS of position (Default: `pixel`)
#' @param resampling Resampling algorithm for interpolation. Choices: "nearest", "bilinear", "cubic", "cubicspline" (Default: `nearest`)
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples
#' \dontrun{
#' # TODO: No examples available for gdal_raster_pixel_info.
#' # See GDAL documentation: https://gdal.org/programs/gdal-raster-pixel-info.html
#' job <- gdal_raster_pixel_info()
#' # gdal_job_run(job)
#' }
#' @export
gdal_raster_pixel_info <- function(input,
  input_format = NULL,
  output_format = NULL,
  open_option = NULL,
  band = NULL,
  overview = NULL,
  position = NULL,
  position_crs = NULL,
  resampling = NULL) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(input_format)) new_args[["input_format"]] <- input_format
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(band)) new_args[["band"]] <- band
  if (!missing(overview)) new_args[["overview"]] <- overview
  if (!missing(position)) new_args[["position"]] <- position
  if (!missing(position_crs)) new_args[["position_crs"]] <- position_crs
  if (!missing(resampling)) new_args[["resampling"]] <- resampling

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("raster", "pixel-info"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    input = list(min_count = 0, max_count = 1),
    input_format = list(min_count = 0, max_count = 2147483647),
    output_format = list(min_count = 0, max_count = 1),
    open_option = list(min_count = 0, max_count = 2147483647),
    band = list(min_count = 0, max_count = 2147483647),
    overview = list(min_count = 0, max_count = 1),
    position = list(min_count = 0, max_count = 2147483647),
    position_crs = list(min_count = 0, max_count = 1),
    resampling = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("raster", "pixel-info"), arguments = merged_args, arg_mapping = .arg_mapping)
}

