# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.11.4
# Generation date: 2026-04-15
# ===================================================================

#' @title info: Return information on a multidimensional dataset
#' @description
#' Return information on a multidimensional dataset.
#' 
#' See \url{https://gdal.org/en/3.11.4/programs/gdal_mdim_info.html} for detailed GDAL documentation.
#' @param input Input multidimensional raster dataset (Dataset path) (required). Can also be a [gdal_job] object to extend a pipeline
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>` (Advanced)
#' @param input_format Input formats (Character vector) (Advanced)
#' @param detailed Most verbose output. Report attribute data types and array values. (Logical)
#' @param array Name of the array, used to restrict the output to the specified array.
#' @param limit Number of values in each dimension that is used to limit the display of array values. (Integer)
#' @param array_option Option passed to GDALGroup::GetMDArrayNames() to filter reported arrays. (Character vector). Format: `<KEY>=<VALUE>`
#' @param stats Read and display image statistics. (Logical)
#' @param stdout Directly output on stdout. If enabled, output-string will be empty (Logical)
#' @return A [gdal_job] object.
#' @family gdal_mdim_utilities
#' @examples

#' job <- gdal_mdim_info(input = "netcdf-4d.nc")
#' \dontrun{
#'   result <- gdal_job_run(job)
#' }
#' @export
gdal_mdim_info <- function(input,
  open_option = NULL,
  input_format = NULL,
  detailed = FALSE,
  array = NULL,
  limit = NULL,
  array_option = NULL,
  stats = FALSE,
  stdout = FALSE) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(input_format)) new_args[["input_format"]] <- input_format
  if (!missing(detailed)) new_args[["detailed"]] <- detailed
  if (!missing(array)) new_args[["array"]] <- array
  if (!missing(limit)) new_args[["limit"]] <- limit
  if (!missing(array_option)) new_args[["array_option"]] <- array_option
  if (!missing(stats)) new_args[["stats"]] <- stats
  if (!missing(stdout)) new_args[["stdout"]] <- stdout

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("mdim", "info"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    input = list(min_count = 0, max_count = 1),
    open_option = list(min_count = 0, max_count = 2147483647),
    input_format = list(min_count = 0, max_count = 2147483647),
    detailed = list(min_count = 0, max_count = 1),
    array = list(min_count = 0, max_count = 1),
    limit = list(min_count = 0, max_count = 1),
    array_option = list(min_count = 0, max_count = 2147483647),
    stats = list(min_count = 0, max_count = 1),
    stdout = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("mdim", "info"), arguments = merged_args, arg_mapping = .arg_mapping)
}

