# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.11.4
# Generation date: 2026-04-15
# ===================================================================

#' @title sync: Synchronize source and target file/directory located on GDAL Virtual System...
#' @description
#' Synchronize source and target file/directory located on GDAL Virtual System Interface (VSI).
#' 
#' See \url{https://gdal.org/en/3.11.4/programs/gdal_vsi_sync.html} for detailed GDAL documentation.
#' @param source Source file or directory name (required). Can also be a [gdal_job] object to extend a pipeline
#' @param destination Destination file or directory name (required)
#' @param recursive Synchronize recursively (Logical)
#' @param strategy Synchronization strategy. Choices: "timestamp", "ETag", "overwrite" (Default: `timestamp`)
#' @param num_threads Number of jobs (or ALL_CPUS)
#' @return A [gdal_job] object.
#' @family gdal_vsi_utilities
#' @examples
#' \dontrun{
#' # TODO: No examples available for gdal_vsi_sync.
#' # See GDAL documentation: https://gdal.org/programs/gdal-vsi-sync.html
#' job <- gdal_vsi_sync()
#' # gdal_job_run(job)
#' }
#' @export
gdal_vsi_sync <- function(source,
  destination,
  recursive = FALSE,
  strategy = NULL,
  num_threads = NULL) {
  new_args <- list()
  if (!missing(source)) new_args[["source"]] <- source
  if (!missing(destination)) new_args[["destination"]] <- destination
  if (!missing(recursive)) new_args[["recursive"]] <- recursive
  if (!missing(strategy)) new_args[["strategy"]] <- strategy
  if (!missing(num_threads)) new_args[["num_threads"]] <- num_threads

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(source) && inherits(source, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- source
    new_args[["source"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("vsi", "sync"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    source = list(min_count = 0, max_count = 1),
    destination = list(min_count = 0, max_count = 1),
    recursive = list(min_count = 0, max_count = 1),
    strategy = list(min_count = 0, max_count = 1),
    num_threads = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("vsi", "sync"), arguments = merged_args, arg_mapping = .arg_mapping)
}

