# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.11.4
# Generation date: 2026-04-24
# ===================================================================

#' @title info: Return information on a raster dataset
#' @description
#' `gdal raster info` lists various information about a GDAL supported raster dataset. The following items will be reported (when known): - The format driver used to access the file. - Raster size (in pixels and lines). - The coordinate system for the file (in OGC WKT). - The geotransform associated with the file (rotational coefficients are currently not reported). - Corner coordinates in georeferenced, and if possible lat/long based on the full geotransform (but not GCPs). - Ground control points. - File wide (including subdatasets) metadata. - Band data types. - Band color interpretations. - Band block size. - Band descriptions. - Band min/max values (internally known and possibly computed). - Band checksum (if computation asked). - Band NODATA value. - Band overview resolutions available. - Band unit type (i.e.. "meters" or "feet" for elevation bands). - Band pseudo-color tables. Starting with GDAL 3.12, gdal raster info can be used as the last step of a pipeline. The following options are available:
#' 
#' See \url{https://gdal.org/en/release-3.11/programs/gdal_raster_info.html} for detailed GDAL documentation.
#' @param input Input raster dataset (Dataset path) (required). Can also be a [gdal_job] object to extend a pipeline
#' @param input_format Input formats (Character vector) (Advanced)
#' @param output_format Output format. Choices: "json", "text" (Default: `json`)
#' @param min_max Compute minimum and maximum value (Logical)
#' @param stats Retrieve or compute statistics, using all pixels (Logical)
#' @param approx_stats Retrieve or compute statistics, using a subset of pixels (Logical)
#' @param hist Retrieve or compute histogram (Logical)
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>` (Advanced)
#' @param no_gcp Suppress ground control points list printing (Logical) (Advanced)
#' @param no_md Suppress metadata printing (Logical) (Advanced)
#' @param no_ct Suppress color table printing (Logical) (Advanced)
#' @param no_fl Suppress file list printing (Logical) (Advanced)
#' @param checksum Compute pixel checksum (Logical) (Advanced)
#' @param list_mdd List all metadata domains available for the dataset (Logical) (Advanced)
#' @param metadata_domain Report metadata for the specified domain. 'all' can be used to report metadata in all domains (Advanced)
#' @param no_nodata Suppress retrieving nodata value (Logical) (Esoteric)
#' @param no_mask Suppress mask band information (Logical) (Esoteric)
#' @param subdataset Use subdataset of specified index (starting at 1), instead of the source dataset itself (Integer). Minimum: `1` (Esoteric)
#' @param stdout Directly output on stdout (format=text mode only). If enabled, output-string will be empty (Logical)
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples

#' job <- gdal_raster_info(input = "utmsmall.tif")
#' \dontrun{
#'   result <- gdal_job_run(job)
#' }
#' @export
gdal_raster_info <- function(input,
  input_format = NULL,
  output_format = NULL,
  min_max = FALSE,
  stats = FALSE,
  approx_stats = FALSE,
  hist = FALSE,
  open_option = NULL,
  no_gcp = FALSE,
  no_md = FALSE,
  no_ct = FALSE,
  no_fl = FALSE,
  checksum = FALSE,
  list_mdd = FALSE,
  metadata_domain = NULL,
  no_nodata = FALSE,
  no_mask = FALSE,
  subdataset = NULL,
  stdout = FALSE) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(input_format)) new_args[["input_format"]] <- input_format
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(min_max)) new_args[["min_max"]] <- min_max
  if (!missing(stats)) new_args[["stats"]] <- stats
  if (!missing(approx_stats)) new_args[["approx_stats"]] <- approx_stats
  if (!missing(hist)) new_args[["hist"]] <- hist
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(no_gcp)) new_args[["no_gcp"]] <- no_gcp
  if (!missing(no_md)) new_args[["no_md"]] <- no_md
  if (!missing(no_ct)) new_args[["no_ct"]] <- no_ct
  if (!missing(no_fl)) new_args[["no_fl"]] <- no_fl
  if (!missing(checksum)) new_args[["checksum"]] <- checksum
  if (!missing(list_mdd)) new_args[["list_mdd"]] <- list_mdd
  if (!missing(metadata_domain)) new_args[["metadata_domain"]] <- metadata_domain
  if (!missing(no_nodata)) new_args[["no_nodata"]] <- no_nodata
  if (!missing(no_mask)) new_args[["no_mask"]] <- no_mask
  if (!missing(subdataset)) new_args[["subdataset"]] <- subdataset
  if (!missing(stdout)) new_args[["stdout"]] <- stdout

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("raster", "info"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    input = list(min_count = 0, max_count = 1),
    input_format = list(min_count = 0, max_count = 2147483647),
    output_format = list(min_count = 0, max_count = 1),
    min_max = list(min_count = 0, max_count = 1),
    stats = list(min_count = 0, max_count = 1),
    approx_stats = list(min_count = 0, max_count = 1),
    hist = list(min_count = 0, max_count = 1),
    open_option = list(min_count = 0, max_count = 2147483647),
    no_gcp = list(min_count = 0, max_count = 1),
    no_md = list(min_count = 0, max_count = 1),
    no_ct = list(min_count = 0, max_count = 1),
    no_fl = list(min_count = 0, max_count = 1),
    checksum = list(min_count = 0, max_count = 1),
    list_mdd = list(min_count = 0, max_count = 1),
    metadata_domain = list(min_count = 0, max_count = 1),
    no_nodata = list(min_count = 0, max_count = 1),
    no_mask = list(min_count = 0, max_count = 1),
    subdataset = list(min_count = 0, max_count = 1),
    stdout = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("raster", "info"), arguments = merged_args, arg_mapping = .arg_mapping)
}

