# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.11.4
# Generation date: 2026-04-24
# ===================================================================

#' @title contour: Creates a vector contour from a raster elevation model (DEM)
#' @description
#' `gdal raster contour` creates a vector contour from a raster elevation model (DEM). Since GDAL 3.12, this algorithm can be part of a gdal_pipeline. The following options are available:
#' 
#' See \url{https://gdal.org/en/release-3.11/programs/gdal_raster_contour.html} for detailed GDAL documentation.
#' @param input Input raster dataset (Dataset path) (required). Can also be a [gdal_job] object to extend a pipeline
#' @param input_format Input formats (Character vector) (Advanced)
#' @param output Output vector dataset (Dataset path) (required)
#' @param output_format Output format
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>` (Advanced)
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`
#' @param layer_creation_option Layer creation option (Character vector). Format: `<KEY>=<VALUE>`
#' @param band Input band (1-based index) (Integer) (Default: `1`)
#' @param layer Layer name
#' @param elevation_name Name of the elevation field
#' @param min_name Name of the minimum elevation field
#' @param max_name Name of the maximum elevation field
#' @param X3d Force production of 3D vectors instead of 2D (Logical)
#' @param src_nodata Input pixel value to treat as 'nodata'
#' @param interval Elevation interval between contours. Minimum: `0`
#' @param levels List of contour levels (Character vector)
#' @param exp_base Base for exponential contour level generation (Integer)
#' @param offset Offset to apply to contour levels
#' @param polygonize Create polygons instead of lines (Logical)
#' @param group_transactions Group n features per transaction (default 100 000) (Integer). Minimum: `0`
#' @param overwrite Whether overwriting existing output is allowed (Logical) (Default: `false`)
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples

#' job <- gdal_raster_contour(input = "elevation.tif", output = "contour.shp", interval = 100)
#' \dontrun{
#'   result <- gdal_job_run(job)
#' }
#' @export
gdal_raster_contour <- function(input,
  input_format = NULL,
  output,
  output_format = NULL,
  open_option = NULL,
  creation_option = NULL,
  layer_creation_option = NULL,
  band = NULL,
  layer = NULL,
  elevation_name = NULL,
  min_name = NULL,
  max_name = NULL,
  X3d = FALSE,
  src_nodata = NULL,
  interval = NULL,
  levels = NULL,
  exp_base = NULL,
  offset = NULL,
  polygonize = FALSE,
  group_transactions = NULL,
  overwrite = FALSE) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(input_format)) new_args[["input_format"]] <- input_format
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(creation_option)) new_args[["creation_option"]] <- creation_option
  if (!missing(layer_creation_option)) new_args[["layer_creation_option"]] <- layer_creation_option
  if (!missing(band)) new_args[["band"]] <- band
  if (!missing(layer)) new_args[["layer"]] <- layer
  if (!missing(elevation_name)) new_args[["elevation_name"]] <- elevation_name
  if (!missing(min_name)) new_args[["min_name"]] <- min_name
  if (!missing(max_name)) new_args[["max_name"]] <- max_name
  if (!missing(X3d)) new_args[["X3d"]] <- X3d
  if (!missing(src_nodata)) new_args[["src_nodata"]] <- src_nodata
  if (!missing(interval)) new_args[["interval"]] <- interval
  if (!missing(levels)) new_args[["levels"]] <- levels
  if (!missing(exp_base)) new_args[["exp_base"]] <- exp_base
  if (!missing(offset)) new_args[["offset"]] <- offset
  if (!missing(polygonize)) new_args[["polygonize"]] <- polygonize
  if (!missing(group_transactions)) new_args[["group_transactions"]] <- group_transactions
  if (!missing(overwrite)) new_args[["overwrite"]] <- overwrite

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("raster", "contour"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    input = list(min_count = 0, max_count = 1),
    input_format = list(min_count = 0, max_count = 2147483647),
    output = list(min_count = 0, max_count = 1),
    output_format = list(min_count = 0, max_count = 1),
    open_option = list(min_count = 0, max_count = 2147483647),
    creation_option = list(min_count = 0, max_count = 2147483647),
    layer_creation_option = list(min_count = 0, max_count = 2147483647),
    band = list(min_count = 0, max_count = 1),
    layer = list(min_count = 0, max_count = 1),
    elevation_name = list(min_count = 0, max_count = 1),
    min_name = list(min_count = 0, max_count = 1),
    max_name = list(min_count = 0, max_count = 1),
    X3d = list(min_count = 0, max_count = 1),
    src_nodata = list(min_count = 0, max_count = 1),
    interval = list(min_count = 0, max_count = 1),
    levels = list(min_count = 0, max_count = 2147483647),
    exp_base = list(min_count = 0, max_count = 1),
    offset = list(min_count = 0, max_count = 1),
    polygonize = list(min_count = 0, max_count = 1),
    group_transactions = list(min_count = 0, max_count = 1),
    overwrite = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("raster", "contour"), arguments = merged_args, arg_mapping = .arg_mapping)
}

