# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.11.4
# Generation date: 2026-04-21
# ===================================================================

#' @title explode-collections: Explode geometries of type collection of a vector
#' dataset
#' @description
#' Explode geometries of type collection of a vector dataset.
#' 
#' See
#' \url{https://gdal.org/en/release-3.11/programs/gdal_vector_geom_explode-collections.html}
#' for detailed GDAL documentation.
#' @param input Input vector datasets (required). Exactly `1` value(s). Can also be a
#' [gdal_job] object to extend a pipeline
#' @param input_format Input formats (Character vector) (Advanced)
#' @param input_layer Input layer name(s) (Character vector)
#' @param output Output vector dataset (Dataset path) (required)
#' @param output_format Output format ("GDALG" allowed)
#' @param output_layer Output layer name
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>`
#' (Advanced)
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`
#' @param layer_creation_option Layer creation option (Character vector). Format:
#' `<KEY>=<VALUE>`
#' @param overwrite Whether overwriting existing output is allowed (Logical) (Default:
#' `false`)
#' @param update Whether to open existing dataset in update mode (Logical) (Default:
#' `false`)
#' @param overwrite_layer Whether overwriting existing layer is allowed (Logical)
#' (Default: `false`)
#' @param append Whether appending to existing layer is allowed (Logical) (Default:
#' `false`)
#' @param active_layer Set active layer (if not specified, all)
#' @param active_geometry Geometry field name to which to restrict the processing (if
#' not specified, all)
#' @param geometry_type Geometry type
#' @param skip_on_type_mismatch Skip feature when change of feature geometry type
#' failed (Logical)
#' @return A [gdal_job] object.
#' @family gdal_vector_utilities
#' @examples
#' \dontrun{
#' # TODO: No examples available for gdal_vector_geom_explode_collections.
#' # See GDAL documentation:
#' https://gdal.org/programs/gdal-vector-geom-explode-collections.html
#' job <- gdal_vector_geom_explode_collections()
#' # gdal_job_run(job)
#' }
#' @export
gdal_vector_geom_explode_collections <- function(input,
  input_format = NULL,
  input_layer = NULL,
  output,
  output_format = NULL,
  output_layer = NULL,
  open_option = NULL,
  creation_option = NULL,
  layer_creation_option = NULL,
  overwrite = FALSE,
  update = FALSE,
  overwrite_layer = FALSE,
  append = FALSE,
  active_layer = NULL,
  active_geometry = NULL,
  geometry_type = NULL,
  skip_on_type_mismatch = FALSE) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(input_format)) new_args[["input_format"]] <- input_format
  if (!missing(input_layer)) new_args[["input_layer"]] <- input_layer
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(output_layer)) new_args[["output_layer"]] <- output_layer
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(creation_option)) new_args[["creation_option"]] <- creation_option
  if (!missing(layer_creation_option)) new_args[["layer_creation_option"]] <- layer_creation_option
  if (!missing(overwrite)) new_args[["overwrite"]] <- overwrite
  if (!missing(update)) new_args[["update"]] <- update
  if (!missing(overwrite_layer)) new_args[["overwrite_layer"]] <- overwrite_layer
  if (!missing(append)) new_args[["append"]] <- append
  if (!missing(active_layer)) new_args[["active_layer"]] <- active_layer
  if (!missing(active_geometry)) new_args[["active_geometry"]] <- active_geometry
  if (!missing(geometry_type)) new_args[["geometry_type"]] <- geometry_type
  if (!missing(skip_on_type_mismatch)) new_args[["skip_on_type_mismatch"]] <- skip_on_type_mismatch

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("vector", "geom", "explode-collections"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    input = list(min_count = 1, max_count = 1),
    input_format = list(min_count = 0, max_count = 2147483647),
    input_layer = list(min_count = 0, max_count = 2147483647),
    output = list(min_count = 0, max_count = 1),
    output_format = list(min_count = 0, max_count = 1),
    output_layer = list(min_count = 0, max_count = 1),
    open_option = list(min_count = 0, max_count = 2147483647),
    creation_option = list(min_count = 0, max_count = 2147483647),
    layer_creation_option = list(min_count = 0, max_count = 2147483647),
    overwrite = list(min_count = 0, max_count = 1),
    update = list(min_count = 0, max_count = 1),
    overwrite_layer = list(min_count = 0, max_count = 1),
    append = list(min_count = 0, max_count = 1),
    active_layer = list(min_count = 0, max_count = 1),
    active_geometry = list(min_count = 0, max_count = 1),
    geometry_type = list(min_count = 0, max_count = 1),
    skip_on_type_mismatch = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("vector", "geom", "explode-collections"), arguments = merged_args, arg_mapping = .arg_mapping)
}

