# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.11.4
# Generation date: 2026-04-15
# ===================================================================

#' @title create: Create an index of raster datasets compatible of the GDAL Tile Index (GTI)...
#' @description
#' Create an index of raster datasets compatible of the GDAL Tile Index (GTI) driver.
#' 
#' See \url{https://gdal.org/en/3.11.4/programs/gdal_driver_gti_create.html} for detailed GDAL documentation.
#' @param input Input raster datasets (required). Can also be a [gdal_job] object to extend a pipeline
#' @param output Output vector dataset (Dataset path) (required)
#' @param output_format Output format
#' @param output_data_type Datatype of the virtual mosaic. Choices: "Byte", "Int8", "UInt16", "Int16", "UInt32", ...
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`
#' @param layer_creation_option Layer creation option (Character vector). Format: `<KEY>=<VALUE>`
#' @param overwrite Whether overwriting existing output is allowed (Logical) (Default: `false`)
#' @param update Whether to open existing dataset in update mode (Logical) (Default: `false`)
#' @param overwrite_layer Whether overwriting existing layer is allowed (Logical) (Default: `false`)
#' @param append Whether appending to existing layer is allowed (Logical) (Default: `false`)
#' @param layer Layer name
#' @param recursive Whether input directories should be explored recursively. (Logical)
#' @param filename_filter Pattern that the filenames in input directories should follow ('*' and '?' wildcard) (Character vector)
#' @param min_pixel_size Minimum pixel size in term of geospatial extent per pixel (resolution) that a raster should have to be selected.. Minimum: `0`
#' @param max_pixel_size Maximum pixel size in term of geospatial extent per pixel (resolution) that a raster should have to be selected.. Minimum: `0`
#' @param location_name Name of the field with the raster path (Default: `location`)
#' @param absolute_path Whether the path to the input datasets should be stored as an absolute path (Logical)
#' @param dst_crs Destination CRS
#' @param metadata Add dataset metadata item (Character vector). Format: `<KEY>=<VALUE>`
#' @param xml_filename Filename of the XML Virtual Tile Index file to generate, that can be used as an input for the GDAL GTI / Virtual Raster Tile Index driver
#' @param resolution Resolution (in destination CRS units) of the virtual mosaic. Format: `<xres>,<yres>`. Minimum: `0`. Exactly `2` value(s)
#' @param bbox Bounding box (in destination CRS units) of the virtual mosaic. Exactly `4` value(s)
#' @param band_count Number of bands of the virtual mosaic (Integer). Minimum: `1`
#' @param nodata Nodata value(s) of the bands of the virtual mosaic
#' @param color_interpretation Color interpretation(s) of the bands of the virtual mosaic (Character vector). Choices: "red", "green", "blue", "alpha", "gray", ...
#' @param mask Defines that the virtual mosaic has a mask band (Logical)
#' @param fetch_metadata Fetch a metadata item from source rasters and write it as a field in the index. (Character vector). Format: `<gdal-metadata-name>,<field-name>,<field-type>`
#' @return A [gdal_job] object.
#' @family gdal_driver_utilities
#' @examples

#' job <- gdal_driver_gti_create(input = "*.tif", output = "tile_index.gti.gpkg", 
#'     resolution = c(60, 60), band_count = 3, color_interpretation = "Red,Green,Blue")
#' \dontrun{
#'   result <- gdal_job_run(job)
#' }
#' @export
gdal_driver_gti_create <- function(input,
  output,
  output_format = NULL,
  output_data_type = NULL,
  creation_option = NULL,
  layer_creation_option = NULL,
  overwrite = FALSE,
  update = FALSE,
  overwrite_layer = FALSE,
  append = FALSE,
  layer = NULL,
  recursive = FALSE,
  filename_filter = NULL,
  min_pixel_size = NULL,
  max_pixel_size = NULL,
  location_name = NULL,
  absolute_path = FALSE,
  dst_crs = NULL,
  metadata = NULL,
  xml_filename = NULL,
  resolution = NULL,
  bbox = NULL,
  band_count = NULL,
  nodata = NULL,
  color_interpretation = NULL,
  mask = FALSE,
  fetch_metadata = NULL) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(output_data_type)) new_args[["output_data_type"]] <- output_data_type
  if (!missing(creation_option)) new_args[["creation_option"]] <- creation_option
  if (!missing(layer_creation_option)) new_args[["layer_creation_option"]] <- layer_creation_option
  if (!missing(overwrite)) new_args[["overwrite"]] <- overwrite
  if (!missing(update)) new_args[["update"]] <- update
  if (!missing(overwrite_layer)) new_args[["overwrite_layer"]] <- overwrite_layer
  if (!missing(append)) new_args[["append"]] <- append
  if (!missing(layer)) new_args[["layer"]] <- layer
  if (!missing(recursive)) new_args[["recursive"]] <- recursive
  if (!missing(filename_filter)) new_args[["filename_filter"]] <- filename_filter
  if (!missing(min_pixel_size)) new_args[["min_pixel_size"]] <- min_pixel_size
  if (!missing(max_pixel_size)) new_args[["max_pixel_size"]] <- max_pixel_size
  if (!missing(location_name)) new_args[["location_name"]] <- location_name
  if (!missing(absolute_path)) new_args[["absolute_path"]] <- absolute_path
  if (!missing(dst_crs)) new_args[["dst_crs"]] <- dst_crs
  if (!missing(metadata)) new_args[["metadata"]] <- metadata
  if (!missing(xml_filename)) new_args[["xml_filename"]] <- xml_filename
  if (!missing(resolution)) new_args[["resolution"]] <- resolution
  if (!missing(bbox)) new_args[["bbox"]] <- bbox
  if (!missing(band_count)) new_args[["band_count"]] <- band_count
  if (!missing(nodata)) new_args[["nodata"]] <- nodata
  if (!missing(color_interpretation)) new_args[["color_interpretation"]] <- color_interpretation
  if (!missing(mask)) new_args[["mask"]] <- mask
  if (!missing(fetch_metadata)) new_args[["fetch_metadata"]] <- fetch_metadata

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("driver", "gti", "create"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    input = list(min_count = 0, max_count = 2147483647),
    output = list(min_count = 0, max_count = 1),
    output_format = list(min_count = 0, max_count = 1),
    output_data_type = list(min_count = 0, max_count = 1),
    creation_option = list(min_count = 0, max_count = 2147483647),
    layer_creation_option = list(min_count = 0, max_count = 2147483647),
    overwrite = list(min_count = 0, max_count = 1),
    update = list(min_count = 0, max_count = 1),
    overwrite_layer = list(min_count = 0, max_count = 1),
    append = list(min_count = 0, max_count = 1),
    layer = list(min_count = 0, max_count = 1),
    recursive = list(min_count = 0, max_count = 1),
    filename_filter = list(min_count = 0, max_count = 2147483647),
    min_pixel_size = list(min_count = 0, max_count = 1),
    max_pixel_size = list(min_count = 0, max_count = 1),
    location_name = list(min_count = 0, max_count = 1),
    absolute_path = list(min_count = 0, max_count = 1),
    dst_crs = list(min_count = 0, max_count = 1),
    metadata = list(min_count = 0, max_count = 2147483647),
    xml_filename = list(min_count = 0, max_count = 1),
    resolution = list(min_count = 2, max_count = 2),
    bbox = list(min_count = 4, max_count = 4),
    band_count = list(min_count = 0, max_count = 1),
    nodata = list(min_count = 0, max_count = 2147483647),
    color_interpretation = list(min_count = 0, max_count = 2147483647),
    mask = list(min_count = 0, max_count = 1),
    fetch_metadata = list(min_count = 0, max_count = 2147483647)
  )

  new_gdal_job(command_path = c("driver", "gti", "create"), arguments = merged_args, arg_mapping = .arg_mapping)
}

