# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.11.4
# Generation date: 2026-04-24
# ===================================================================

#' @title Process a vector dataset
#' @description
#' `gdal vector pipeline` can be used to process a vector dataset and perform various processing steps that accept vector and generate vector. For pipelines mixing raster and vector, consult gdal_pipeline. Most steps proceed in on-demand evaluation of features, unless otherwise stated in their documentation, without "materializing" the resulting dataset of the operation of each step. It may be desirable sometimes for performance purposes to proceed to materializing an intermediate dataset to disk using gdal_vector_materialize.
#' 
#' See \url{https://gdal.org/en/release-3.11/programs/gdal_vector_pipeline.html} for detailed GDAL documentation.
#' @param jobs A vector of gdal_job objects to execute in sequence, or NULL to use pipeline string
#' @param input Input vector datasets. `1` to `2147483647` value(s)
#' @param input_format Input formats (Character vector) (Advanced)
#' @param input_layer Input layer name(s) (Character vector)
#' @param output Output vector dataset (Dataset path)
#' @param output_format Output format ("GDALG" allowed)
#' @param output_layer Output layer name
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>` (Advanced)
#' @param pipeline Pipeline string (ignored if jobs is provided)
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`
#' @param layer_creation_option Layer creation option (Character vector). Format: `<KEY>=<VALUE>`
#' @param overwrite Whether overwriting existing output is allowed (Logical) (Default: `false`)
#' @param update Whether to open existing dataset in update mode (Logical) (Default: `false`)
#' @param overwrite_layer Whether overwriting existing layer is allowed (Logical) (Default: `false`)
#' @param append Whether appending to existing layer is allowed (Logical) (Default: `false`)
#' @return A [gdal_job] object.
#' @family gdal_vector_utilities
#' @examples

#' job <- gdal_vector_pipeline(input = c("in.gpkg", "!", "reproject", "!", "write"), 
#'     output = "out.gpkg", overwrite = TRUE)
#' \dontrun{
#'   result <- gdal_job_run(job)
#' }
#' @export
gdal_vector_pipeline <- function(jobs = NULL,
  input = NULL,
  input_format = NULL,
  input_layer = NULL,
  output = NULL,
  output_format = NULL,
  output_layer = NULL,
  open_option = NULL,
  pipeline = NULL,
  creation_option = NULL,
  layer_creation_option = NULL,
  overwrite = FALSE,
  update = FALSE,
  overwrite_layer = FALSE,
  append = FALSE) {
  # If jobs is provided, build pipeline string from job sequence
  if (!is.null(jobs)) {
    if (!is.list(jobs) && !is.vector(jobs)) {
      rlang::abort('jobs must be a list or vector of gdal_job objects')
    }
    for (i in seq_along(jobs)) {
      if (!inherits(jobs[[i]], 'gdal_job')) {
        rlang::abort(sprintf('jobs[[%d]] must be a gdal_job object', i))
      }
    }
    pipeline <- .build_pipeline_from_jobs(jobs)
  }

  # Collect arguments
  args <- list()
  if (!missing(input)) args[["input"]] <- input
  if (!missing(input_format)) args[["input_format"]] <- input_format
  if (!missing(input_layer)) args[["input_layer"]] <- input_layer
  if (!missing(output)) args[["output"]] <- output
  if (!missing(output_format)) args[["output_format"]] <- output_format
  if (!missing(output_layer)) args[["output_layer"]] <- output_layer
  if (!missing(open_option)) args[["open_option"]] <- open_option
  if (!missing(pipeline)) args[["pipeline"]] <- pipeline
  if (!missing(creation_option)) args[["creation_option"]] <- creation_option
  if (!missing(layer_creation_option)) args[["layer_creation_option"]] <- layer_creation_option
  if (!missing(overwrite)) args[["overwrite"]] <- overwrite
  if (!missing(update)) args[["update"]] <- update
  if (!missing(overwrite_layer)) args[["overwrite_layer"]] <- overwrite_layer
  if (!missing(append)) args[["append"]] <- append

  .arg_mapping <- list(
    input = list(min_count = 1, max_count = 2147483647),
    input_format = list(min_count = 0, max_count = 2147483647),
    input_layer = list(min_count = 0, max_count = 2147483647),
    output = list(min_count = 0, max_count = 1),
    output_format = list(min_count = 0, max_count = 1),
    output_layer = list(min_count = 0, max_count = 1),
    open_option = list(min_count = 0, max_count = 2147483647),
    pipeline = list(min_count = 0, max_count = 1),
    creation_option = list(min_count = 0, max_count = 2147483647),
    layer_creation_option = list(min_count = 0, max_count = 2147483647),
    overwrite = list(min_count = 0, max_count = 1),
    update = list(min_count = 0, max_count = 1),
    overwrite_layer = list(min_count = 0, max_count = 1),
    append = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("vector", "pipeline"), arguments = args, arg_mapping = .arg_mapping)
}

