# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.11.4
# Generation date: 2026-04-24
# ===================================================================

#' @title copy: Copy files located on GDAL Virtual System Interface (VSI)
#' @description
#' `gdal vsi copy` copy files and directories located on virtual_file_systems. It can copy files and directories between different virtual file systems. This is the equivalent of the UNIX ``cp`` command, and ``gdal vsi cp`` is an alias for ``gdal vsi copy``.
#' 
#' See \url{https://gdal.org/en/release-3.11/programs/gdal_vsi_copy.html} for detailed GDAL documentation.
#' @param source Source file or directory name (required). Can also be a [gdal_job] object to extend a pipeline
#' @param destination Destination file or directory name (required)
#' @param recursive Copy subdirectories recursively (Logical)
#' @param skip_errors Skip errors (Logical)
#' @return A [gdal_job] object.
#' @family gdal_vsi_utilities
#' @examples
#' \dontrun{
#' # TODO: No examples available for gdal_vsi_copy.
#' # See GDAL documentation: https://gdal.org/programs/gdal-vsi-copy.html
#' job <- gdal_vsi_copy()
#' # gdal_job_run(job)
#' }
#' @export
gdal_vsi_copy <- function(source,
  destination,
  recursive = FALSE,
  skip_errors = FALSE) {
  new_args <- list()
  if (!missing(source)) new_args[["source"]] <- source
  if (!missing(destination)) new_args[["destination"]] <- destination
  if (!missing(recursive)) new_args[["recursive"]] <- recursive
  if (!missing(skip_errors)) new_args[["skip_errors"]] <- skip_errors

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(source) && inherits(source, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- source
    new_args[["source"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("vsi", "copy"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    source = list(min_count = 0, max_count = 1),
    destination = list(min_count = 0, max_count = 1),
    recursive = list(min_count = 0, max_count = 1),
    skip_errors = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("vsi", "copy"), arguments = merged_args, arg_mapping = .arg_mapping)
}

