# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.11.4
# Generation date: 2026-04-15
# ===================================================================

#' @title linear: Create a regular grid from scattered points using linear/barycentric...
#' @description
#' Create a regular grid from scattered points using linear/barycentric interpolation.
#' 
#' See \url{https://gdal.org/en/3.11.4/programs/gdal_vector_grid_linear.html} for detailed GDAL documentation.
#' @param input Input vector dataset (Dataset path) (required). Can also be a [gdal_job] object to extend a pipeline
#' @param input_format Input formats (Character vector) (Advanced)
#' @param output Output raster dataset (Dataset path) (required)
#' @param output_format Output format
#' @param output_data_type Output data type. Choices: "Byte", "Int8", "UInt16", "Int16", "UInt32", ... (Default: `Float64`)
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>` (Advanced)
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`
#' @param extent Set the target georeferenced extent. Format: `<xmin>,<ymin>,<xmax>,<ymax>`. Exactly `4` value(s)
#' @param resolution Set the target resolution. Format: `<xres>,<yres>`. Exactly `2` value(s)
#' @param size Set the target size in pixels and lines (Integer vector). Format: `<xsize>,<ysize>`. Exactly `2` value(s)
#' @param crs Override the projection for the output file
#' @param overwrite Whether overwriting existing output is allowed (Logical) (Default: `false`)
#' @param layer Layer name (Character vector)
#' @param sql SQL statement. Format: `<statement>|@<filename>`
#' @param bbox Select only points contained within the specified bounding box. Exactly `4` value(s)
#' @param zfield Field name from which to get Z values.
#' @param zoffset Value to add to the Z field value (applied before zmultiply) (Default: `0`)
#' @param zmultiply Multiplication factor for the Z field value (applied after zoffset) (Default: `1`)
#' @param radius Radius of the search circle (Default: `Inf`)
#' @param nodata Target nodata value (Default: `0`)
#' @return A [gdal_job] object.
#' @family gdal_vector_utilities
#' @examples
#' \dontrun{
#' # TODO: No examples available for gdal_vector_grid_linear.
#' # See GDAL documentation: https://gdal.org/programs/gdal-vector-grid-linear.html
#' job <- gdal_vector_grid_linear()
#' # gdal_job_run(job)
#' }
#' @export
gdal_vector_grid_linear <- function(input,
  input_format = NULL,
  output,
  output_format = NULL,
  output_data_type = NULL,
  open_option = NULL,
  creation_option = NULL,
  extent = NULL,
  resolution = NULL,
  size = NULL,
  crs = NULL,
  overwrite = FALSE,
  layer = NULL,
  sql = NULL,
  bbox = NULL,
  zfield = NULL,
  zoffset = NULL,
  zmultiply = NULL,
  radius = NULL,
  nodata = NULL) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(input_format)) new_args[["input_format"]] <- input_format
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(output_data_type)) new_args[["output_data_type"]] <- output_data_type
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(creation_option)) new_args[["creation_option"]] <- creation_option
  if (!missing(extent)) new_args[["extent"]] <- extent
  if (!missing(resolution)) new_args[["resolution"]] <- resolution
  if (!missing(size)) new_args[["size"]] <- size
  if (!missing(crs)) new_args[["crs"]] <- crs
  if (!missing(overwrite)) new_args[["overwrite"]] <- overwrite
  if (!missing(layer)) new_args[["layer"]] <- layer
  if (!missing(sql)) new_args[["sql"]] <- sql
  if (!missing(bbox)) new_args[["bbox"]] <- bbox
  if (!missing(zfield)) new_args[["zfield"]] <- zfield
  if (!missing(zoffset)) new_args[["zoffset"]] <- zoffset
  if (!missing(zmultiply)) new_args[["zmultiply"]] <- zmultiply
  if (!missing(radius)) new_args[["radius"]] <- radius
  if (!missing(nodata)) new_args[["nodata"]] <- nodata

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("vector", "grid", "linear"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    input = list(min_count = 0, max_count = 1),
    input_format = list(min_count = 0, max_count = 2147483647),
    output = list(min_count = 0, max_count = 1),
    output_format = list(min_count = 0, max_count = 1),
    output_data_type = list(min_count = 0, max_count = 1),
    open_option = list(min_count = 0, max_count = 2147483647),
    creation_option = list(min_count = 0, max_count = 2147483647),
    extent = list(min_count = 4, max_count = 4),
    resolution = list(min_count = 2, max_count = 2),
    size = list(min_count = 2, max_count = 2),
    crs = list(min_count = 0, max_count = 1),
    overwrite = list(min_count = 0, max_count = 1),
    layer = list(min_count = 0, max_count = 2147483647),
    sql = list(min_count = 0, max_count = 1),
    bbox = list(min_count = 4, max_count = 4),
    zfield = list(min_count = 0, max_count = 1),
    zoffset = list(min_count = 0, max_count = 1),
    zmultiply = list(min_count = 0, max_count = 1),
    radius = list(min_count = 0, max_count = 1),
    nodata = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("vector", "grid", "linear"), arguments = merged_args, arg_mapping = .arg_mapping)
}

