# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.11.4
# Generation date: 2026-04-15
# ===================================================================

#' @title aspect: Generate an aspect map
#' @description
#' Generate an aspect map
#' 
#' See \url{https://gdal.org/en/3.11.4/programs/gdal_raster_aspect.html} for detailed GDAL documentation.
#' @param input Input raster dataset (Dataset path) (required). Can also be a [gdal_job] object to extend a pipeline
#' @param input_format Input formats (Character vector) (Advanced)
#' @param output Output raster dataset (Dataset path) (required)
#' @param output_format Output format ("GDALG" allowed)
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>` (Advanced)
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`
#' @param overwrite Whether overwriting existing output is allowed (Logical) (Default: `false`)
#' @param band Input band (1-based index) (Integer) (Default: `1`)
#' @param convention Convention for output angles. Choices: "azimuth", "trigonometric-angle" (Default: `azimuth`)
#' @param gradient_alg Algorithm used to compute terrain gradient. Choices: "Horn", "ZevenbergenThorne" (Default: `Horn`)
#' @param zero_for_flat Whether to output zero for flat areas (Logical)
#' @param no_edges Do not try to interpolate values at dataset edges or close to nodata values (Logical)
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples

#' job <- gdal_raster_aspect(input = "n43.dt0", output = "out.tif", overwrite = TRUE)
#' \dontrun{
#'   result <- gdal_job_run(job)
#' }
#' @export
gdal_raster_aspect <- function(input,
  input_format = NULL,
  output,
  output_format = NULL,
  open_option = NULL,
  creation_option = NULL,
  overwrite = FALSE,
  band = NULL,
  convention = NULL,
  gradient_alg = NULL,
  zero_for_flat = FALSE,
  no_edges = FALSE) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(input_format)) new_args[["input_format"]] <- input_format
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(creation_option)) new_args[["creation_option"]] <- creation_option
  if (!missing(overwrite)) new_args[["overwrite"]] <- overwrite
  if (!missing(band)) new_args[["band"]] <- band
  if (!missing(convention)) new_args[["convention"]] <- convention
  if (!missing(gradient_alg)) new_args[["gradient_alg"]] <- gradient_alg
  if (!missing(zero_for_flat)) new_args[["zero_for_flat"]] <- zero_for_flat
  if (!missing(no_edges)) new_args[["no_edges"]] <- no_edges

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("raster", "aspect"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    input = list(min_count = 0, max_count = 1),
    input_format = list(min_count = 0, max_count = 2147483647),
    output = list(min_count = 0, max_count = 1),
    output_format = list(min_count = 0, max_count = 1),
    open_option = list(min_count = 0, max_count = 2147483647),
    creation_option = list(min_count = 0, max_count = 2147483647),
    overwrite = list(min_count = 0, max_count = 1),
    band = list(min_count = 0, max_count = 1),
    convention = list(min_count = 0, max_count = 1),
    gradient_alg = list(min_count = 0, max_count = 1),
    zero_for_flat = list(min_count = 0, max_count = 1),
    no_edges = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("raster", "aspect"), arguments = merged_args, arg_mapping = .arg_mapping)
}

