# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.11.4
# Generation date: 2026-04-15
# ===================================================================

#' @title footprint: Compute the footprint of a raster dataset
#' @description
#' Compute the footprint of a raster dataset.
#' 
#' See \url{https://gdal.org/en/3.11.4/programs/gdal_raster_footprint.html} for detailed GDAL documentation.
#' @param input Input raster dataset (Dataset path) (required). Can also be a [gdal_job] object to extend a pipeline
#' @param input_format Input formats (Character vector) (Advanced)
#' @param output Output vector dataset (Dataset path) (required)
#' @param output_format Output format
#' @param output_layer Output layer name (Default: `footprint`)
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>` (Advanced)
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`
#' @param layer_creation_option Layer creation option (Character vector). Format: `<KEY>=<VALUE>`
#' @param append Whether to append to an existing dataset (Logical) (Default: `false`)
#' @param overwrite Whether overwriting existing output is allowed (Logical) (Default: `false`)
#' @param band Input band(s) (1-based index) (Integer vector)
#' @param combine_bands Defines how the mask bands of the selected bands are combined to generate a single mask band, before being vectorized.. Choices: "union", "intersection" (Default: `union`)
#' @param overview Which overview level of source file must be used (Integer). Minimum: `0`
#' @param src_nodata Set nodata values for input bands.. `1` to `2147483647` value(s)
#' @param coordinate_system Target coordinate system. Choices: "georeferenced", "pixel"
#' @param dst_crs Destination CRS
#' @param split_multipolygons Whether to split multipolygons as several features each with one single polygon (Logical)
#' @param convex_hull Whether to compute the convex hull of the footprint (Logical)
#' @param densify_distance Maximum distance between 2 consecutive points of the output geometry.. Minimum: `0`
#' @param simplify_tolerance Tolerance used to merge consecutive points of the output geometry.. Minimum: `0`
#' @param min_ring_area Minimum value for the area of a ring. Minimum: `0`
#' @param max_points Maximum number of points of each output geometry (Default: `100`)
#' @param location_field Name of the field where the path of the input dataset will be stored. (Default: `location`)
#' @param no_location_field Disable creating a field with the path of the input dataset (Logical)
#' @param absolute_path Whether the path to the input dataset should be stored as an absolute path (Logical)
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples

#' job <- gdal_raster_footprint(input = "my_raster.tif", output = "footprint.geojson")
#' \dontrun{
#'   result <- gdal_job_run(job)
#' }
#' @export
gdal_raster_footprint <- function(input,
  input_format = NULL,
  output,
  output_format = NULL,
  output_layer = NULL,
  open_option = NULL,
  creation_option = NULL,
  layer_creation_option = NULL,
  append = FALSE,
  overwrite = FALSE,
  band = NULL,
  combine_bands = NULL,
  overview = NULL,
  src_nodata = NULL,
  coordinate_system = NULL,
  dst_crs = NULL,
  split_multipolygons = FALSE,
  convex_hull = FALSE,
  densify_distance = NULL,
  simplify_tolerance = NULL,
  min_ring_area = NULL,
  max_points = NULL,
  location_field = NULL,
  no_location_field = FALSE,
  absolute_path = FALSE) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(input_format)) new_args[["input_format"]] <- input_format
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(output_layer)) new_args[["output_layer"]] <- output_layer
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(creation_option)) new_args[["creation_option"]] <- creation_option
  if (!missing(layer_creation_option)) new_args[["layer_creation_option"]] <- layer_creation_option
  if (!missing(append)) new_args[["append"]] <- append
  if (!missing(overwrite)) new_args[["overwrite"]] <- overwrite
  if (!missing(band)) new_args[["band"]] <- band
  if (!missing(combine_bands)) new_args[["combine_bands"]] <- combine_bands
  if (!missing(overview)) new_args[["overview"]] <- overview
  if (!missing(src_nodata)) new_args[["src_nodata"]] <- src_nodata
  if (!missing(coordinate_system)) new_args[["coordinate_system"]] <- coordinate_system
  if (!missing(dst_crs)) new_args[["dst_crs"]] <- dst_crs
  if (!missing(split_multipolygons)) new_args[["split_multipolygons"]] <- split_multipolygons
  if (!missing(convex_hull)) new_args[["convex_hull"]] <- convex_hull
  if (!missing(densify_distance)) new_args[["densify_distance"]] <- densify_distance
  if (!missing(simplify_tolerance)) new_args[["simplify_tolerance"]] <- simplify_tolerance
  if (!missing(min_ring_area)) new_args[["min_ring_area"]] <- min_ring_area
  if (!missing(max_points)) new_args[["max_points"]] <- max_points
  if (!missing(location_field)) new_args[["location_field"]] <- location_field
  if (!missing(no_location_field)) new_args[["no_location_field"]] <- no_location_field
  if (!missing(absolute_path)) new_args[["absolute_path"]] <- absolute_path

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("raster", "footprint"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    input = list(min_count = 0, max_count = 1),
    input_format = list(min_count = 0, max_count = 2147483647),
    output = list(min_count = 0, max_count = 1),
    output_format = list(min_count = 0, max_count = 1),
    output_layer = list(min_count = 0, max_count = 1),
    open_option = list(min_count = 0, max_count = 2147483647),
    creation_option = list(min_count = 0, max_count = 2147483647),
    layer_creation_option = list(min_count = 0, max_count = 2147483647),
    append = list(min_count = 0, max_count = 1),
    overwrite = list(min_count = 0, max_count = 1),
    band = list(min_count = 0, max_count = 2147483647),
    combine_bands = list(min_count = 0, max_count = 1),
    overview = list(min_count = 0, max_count = 1),
    src_nodata = list(min_count = 1, max_count = 2147483647),
    coordinate_system = list(min_count = 0, max_count = 1),
    dst_crs = list(min_count = 0, max_count = 1),
    split_multipolygons = list(min_count = 0, max_count = 1),
    convex_hull = list(min_count = 0, max_count = 1),
    densify_distance = list(min_count = 0, max_count = 1),
    simplify_tolerance = list(min_count = 0, max_count = 1),
    min_ring_area = list(min_count = 0, max_count = 1),
    max_points = list(min_count = 0, max_count = 1),
    location_field = list(min_count = 0, max_count = 1),
    no_location_field = list(min_count = 0, max_count = 1),
    absolute_path = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("raster", "footprint"), arguments = merged_args, arg_mapping = .arg_mapping)
}

