# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.11.4
# Generation date: 2026-04-15
# ===================================================================

#' @title sieve: Remove small polygons from a raster dataset
#' @description
#' Remove small polygons from a raster dataset.
#' 
#' See \url{https://gdal.org/en/3.11.4/programs/gdal_raster_sieve.html} for detailed GDAL documentation.
#' @param input Input raster dataset (Dataset path) (required). Can also be a [gdal_job] object to extend a pipeline
#' @param input_format Input formats (Character vector) (Advanced)
#' @param output Output raster dataset (Dataset path) (required)
#' @param output_format Output format
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>` (Advanced)
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`
#' @param overwrite Whether overwriting existing output is allowed (Logical) (Default: `false`)
#' @param mask Use the first band of the specified file as a validity mask (all pixels with a value other than zero will be considered suitable for inclusion in polygons) (Dataset path)
#' @param band Input band (1-based index) (Integer)
#' @param size_threshold Minimum size of polygons to keep (Integer) (Default: `2`)
#' @param connect_diagonal_pixels Consider diagonal pixels as connected (Logical) (Default: `false`)
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples

#' job <- gdal_raster_sieve(input = "input.tif", output = "output.tif")
#' \dontrun{
#'   result <- gdal_job_run(job)
#' }
#' @export
gdal_raster_sieve <- function(input,
  input_format = NULL,
  output,
  output_format = NULL,
  open_option = NULL,
  creation_option = NULL,
  overwrite = FALSE,
  mask = NULL,
  band = NULL,
  size_threshold = NULL,
  connect_diagonal_pixels = FALSE) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(input_format)) new_args[["input_format"]] <- input_format
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(creation_option)) new_args[["creation_option"]] <- creation_option
  if (!missing(overwrite)) new_args[["overwrite"]] <- overwrite
  if (!missing(mask)) new_args[["mask"]] <- mask
  if (!missing(band)) new_args[["band"]] <- band
  if (!missing(size_threshold)) new_args[["size_threshold"]] <- size_threshold
  if (!missing(connect_diagonal_pixels)) new_args[["connect_diagonal_pixels"]] <- connect_diagonal_pixels

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("raster", "sieve"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    input = list(min_count = 0, max_count = 1),
    input_format = list(min_count = 0, max_count = 2147483647),
    output = list(min_count = 0, max_count = 1),
    output_format = list(min_count = 0, max_count = 1),
    open_option = list(min_count = 0, max_count = 2147483647),
    creation_option = list(min_count = 0, max_count = 2147483647),
    overwrite = list(min_count = 0, max_count = 1),
    mask = list(min_count = 0, max_count = 1),
    band = list(min_count = 0, max_count = 1),
    size_threshold = list(min_count = 0, max_count = 1),
    connect_diagonal_pixels = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("raster", "sieve"), arguments = merged_args, arg_mapping = .arg_mapping)
}

