# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.11.4
# Generation date: 2026-04-15
# ===================================================================

#' @title convert: Convert a multidimensional dataset
#' @description
#' Convert a multidimensional dataset.
#' 
#' See \url{https://gdal.org/en/3.11.4/programs/gdal_mdim_convert.html} for detailed GDAL documentation.
#' @param input Input raster or multidimensional raster dataset (Dataset path) (required). Can also be a [gdal_job] object to extend a pipeline
#' @param input_format Input formats (Character vector) (Advanced)
#' @param output Output multidimensional raster dataset (Dataset path) (required)
#' @param output_format Output format
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>` (Advanced)
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`
#' @param overwrite Whether overwriting existing output is allowed (Logical) (Default: `false`)
#' @param array Select a single array instead of converting the whole dataset. (Character vector). Format: `ARRAY-SPEC`
#' @param array_option Option passed to GDALGroup::GetMDArrayNames() to filter arrays. (Character vector). Format: `<KEY>=<VALUE>`
#' @param group Select a single group instead of converting the whole dataset. (Character vector). Format: `GROUP-SPEC`
#' @param subset Select a subset of the data. (Character vector). Format: `SUBSET-SPEC`
#' @param scale_axes Applies a integral scale factor to one or several dimensions (Character vector). Format: `SCALEAXES-SPEC`
#' @param strict Turn warnings into failures. (Logical)
#' @return A [gdal_job] object.
#' @family gdal_mdim_utilities
#' @examples

#' job <- gdal_mdim_convert(input = "in.nc", output = "out.vrt")
#' \dontrun{
#'   result <- gdal_job_run(job)
#' }
#' @export
gdal_mdim_convert <- function(input,
  input_format = NULL,
  output,
  output_format = NULL,
  open_option = NULL,
  creation_option = NULL,
  overwrite = FALSE,
  array = NULL,
  array_option = NULL,
  group = NULL,
  subset = NULL,
  scale_axes = NULL,
  strict = FALSE) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(input_format)) new_args[["input_format"]] <- input_format
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(creation_option)) new_args[["creation_option"]] <- creation_option
  if (!missing(overwrite)) new_args[["overwrite"]] <- overwrite
  if (!missing(array)) new_args[["array"]] <- array
  if (!missing(array_option)) new_args[["array_option"]] <- array_option
  if (!missing(group)) new_args[["group"]] <- group
  if (!missing(subset)) new_args[["subset"]] <- subset
  if (!missing(scale_axes)) new_args[["scale_axes"]] <- scale_axes
  if (!missing(strict)) new_args[["strict"]] <- strict

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("mdim", "convert"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    input = list(min_count = 0, max_count = 1),
    input_format = list(min_count = 0, max_count = 2147483647),
    output = list(min_count = 0, max_count = 1),
    output_format = list(min_count = 0, max_count = 1),
    open_option = list(min_count = 0, max_count = 2147483647),
    creation_option = list(min_count = 0, max_count = 2147483647),
    overwrite = list(min_count = 0, max_count = 1),
    array = list(min_count = 0, max_count = 2147483647),
    array_option = list(min_count = 0, max_count = 2147483647),
    group = list(min_count = 0, max_count = 2147483647),
    subset = list(min_count = 0, max_count = 2147483647),
    scale_axes = list(min_count = 0, max_count = 2147483647),
    strict = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("mdim", "convert"), arguments = merged_args, arg_mapping = .arg_mapping)
}

