# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.11.4
# Generation date: 2026-04-21
# ===================================================================

#' @title list: List content of a ZIP file, with SOZIP related information
#' @description
#' List content of a ZIP file, with SOZIP related information.
#' 
#' See \url{https://gdal.org/en/release-3.11/programs/gdal_vsi_sozip_list.html}
#' for detailed GDAL documentation.
#' @param input Input ZIP filename (required). Can also be a [gdal_job] object to
#' extend a pipeline
#' @return A [gdal_job] object.
#' @family gdal_vsi_utilities
#' @examples
#' \dontrun{
#' # TODO: No examples available for gdal_vsi_sozip_list.
#' # See GDAL documentation: https://gdal.org/programs/gdal-vsi-sozip-list.html
#' job <- gdal_vsi_sozip_list()
#' # gdal_job_run(job)
#' }
#' @export
gdal_vsi_sozip_list <- function(input) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("vsi", "sozip", "list"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    input = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("vsi", "sozip", "list"), arguments = merged_args, arg_mapping = .arg_mapping)
}

