# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.11.4
# Generation date: 2026-04-24
# ===================================================================

#' @title list-layers: List layers of a PDF dataset
#' @description
#' Return the list of layers of a PDF file, as a JSON array or a text list.
#' 
#' See \url{https://gdal.org/en/release-3.11/programs/gdal_driver_pdf_list-layers.html} for detailed GDAL documentation.
#' @param input Input raster or vector dataset (Dataset path) (required). Can also be a [gdal_job] object to extend a pipeline
#' @param output_format Output format. Choices: "json", "text" (Default: `json`)
#' @return A [gdal_job] object.
#' @family gdal_driver_utilities
#' @examples

#' job <- gdal_driver_pdf_list_layers(
#'     input = "autotest/gdrivers/data/pdf/adobe_style_geospatial.pdf")
#' \dontrun{
#'   result <- gdal_job_run(job)
#' }
#' @export
gdal_driver_pdf_list_layers <- function(input,
  output_format = NULL) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(output_format)) new_args[["output_format"]] <- output_format

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("driver", "pdf", "list-layers"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    input = list(min_count = 0, max_count = 1),
    output_format = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("driver", "pdf", "list-layers"), arguments = merged_args, arg_mapping = .arg_mapping)
}

