# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.11.4
# Generation date: 2026-04-15
# ===================================================================

#' @title vector: Vector commands
#' @description
#' Vector commands.
#' 
#' See \url{https://gdal.org/en/3.11.4/programs/gdal_vector.html} for detailed GDAL documentation.
#' @param drivers Display vector driver list as JSON document and exit (Logical). Can also be a [gdal_job] object to extend a pipeline
#' @return A [gdal_job] object.
#' @family gdal_vector_utilities
#' @examples
#' \dontrun{
#' # TODO: No examples available for gdal_vector.
#' # See GDAL documentation: https://gdal.org/programs/gdal-vector.html
#' job <- gdal_vector()
#' # gdal_job_run(job)
#' }
#' @export
gdal_vector <- function(drivers = FALSE) {
  new_args <- list()
  if (!missing(drivers)) new_args[["drivers"]] <- drivers

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(drivers) && inherits(drivers, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- drivers
    new_args[["drivers"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("vector"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    drivers = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("vector"), arguments = merged_args, arg_mapping = .arg_mapping)
}

