# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.11.4
# Generation date: 2026-04-24
# ===================================================================

#' @title edit: Edit a raster dataset
#' @description
#' `gdal raster edit` can be used to edit a raster dataset. This subcommand is also available as a potential step of gdal_raster_pipeline
#' 
#' See \url{https://gdal.org/en/release-3.11/programs/gdal_raster_edit.html} for detailed GDAL documentation.
#' @param dataset Dataset (to be updated in-place, unless --auxiliary) (Dataset path) (required). Can also be a [gdal_job] object to extend a pipeline
#' @param auxiliary Ask for an auxiliary .aux.xml file to be edited (Logical)
#' @param crs Override CRS (without reprojection)
#' @param bbox Bounding box as xmin,ymin,xmax,ymax. Exactly `4` value(s)
#' @param nodata Assign a specified nodata value to output bands ('none', numeric value, 'nan', 'inf', '-inf')
#' @param metadata Add/update dataset metadata item (Character vector). Format: `<KEY>=<VALUE>`
#' @param unset_metadata Remove dataset metadata item (Character vector). Format: `KEY`
#' @param stats Compute statistics, using all pixels (Logical)
#' @param approx_stats Compute statistics, using a subset of pixels (Logical)
#' @param hist Compute histogram (Logical)
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples

#' job <- gdal_raster_edit(dataset = "my.tif", crs = "EPSG:32632")
#' \dontrun{
#'   result <- gdal_job_run(job)
#' }
#' @export
gdal_raster_edit <- function(dataset,
  auxiliary = FALSE,
  crs = NULL,
  bbox = NULL,
  nodata = NULL,
  metadata = NULL,
  unset_metadata = NULL,
  stats = FALSE,
  approx_stats = FALSE,
  hist = FALSE) {
  new_args <- list()
  if (!missing(dataset)) new_args[["dataset"]] <- dataset
  if (!missing(auxiliary)) new_args[["auxiliary"]] <- auxiliary
  if (!missing(crs)) new_args[["crs"]] <- crs
  if (!missing(bbox)) new_args[["bbox"]] <- bbox
  if (!missing(nodata)) new_args[["nodata"]] <- nodata
  if (!missing(metadata)) new_args[["metadata"]] <- metadata
  if (!missing(unset_metadata)) new_args[["unset_metadata"]] <- unset_metadata
  if (!missing(stats)) new_args[["stats"]] <- stats
  if (!missing(approx_stats)) new_args[["approx_stats"]] <- approx_stats
  if (!missing(hist)) new_args[["hist"]] <- hist

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(dataset) && inherits(dataset, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- dataset
    new_args[["dataset"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("raster", "edit"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    dataset = list(min_count = 0, max_count = 1),
    auxiliary = list(min_count = 0, max_count = 1),
    crs = list(min_count = 0, max_count = 1),
    bbox = list(min_count = 4, max_count = 4),
    nodata = list(min_count = 0, max_count = 1),
    metadata = list(min_count = 0, max_count = 2147483647),
    unset_metadata = list(min_count = 0, max_count = 2147483647),
    stats = list(min_count = 0, max_count = 1),
    approx_stats = list(min_count = 0, max_count = 1),
    hist = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("raster", "edit"), arguments = merged_args, arg_mapping = .arg_mapping)
}

