# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.11.4
# Generation date: 2026-04-24
# ===================================================================

#' @title stack: Combine together input bands into a multi-band output, either virtual (VRT) or...
#' @description
#' This program combine together input bands from GDAL datasets into a dataset, that can be either a virtual stack in the VRT (Virtual Dataset) <raster.vrt> format, or in a more conventional raster format such as GeoTIFF. All bands of each input file are added as separate output bands, unless -b is specified to select a subset of them. The list of input GDAL datasets can be specified at the end of the command line or put in a text file (one filename per line) for very long lists. Wildcards '*', '?' or '\['\] of :cppVSIGlob can be used, even on files located on network file systems such as /vsis3/, /vsigs/, /vsiaz/, etc. Stating with GDAL 3.12, this command can also be used as the first step of gdal_raster_pipeline.
#' 
#' See \url{https://gdal.org/en/release-3.11/programs/gdal_raster_stack.html} for detailed GDAL documentation.
#' @param input Input raster datasets (or specify a @<filename> to point to a file containing filenames). Format: `INPUTS`. `1` to `2147483647` value(s). Can also be a [gdal_job] object to extend a pipeline
#' @param output Output raster dataset (Dataset path) (required)
#' @param output_format Output format ("GDALG" allowed)
#' @param target_aligned_pixels Round target extent to target resolution (Logical)
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`
#' @param band Input band(s) (1-based index) (Integer vector)
#' @param overwrite Whether overwriting existing output is allowed (Logical) (Default: `false`)
#' @param resolution Target resolution (in destination CRS units). Format: `<xres>,<yres>|same|average|common|highest|lowest` (Default: `same`)
#' @param bbox Target bounding box as xmin,ymin,xmax,ymax (in destination CRS units). Exactly `4` value(s)
#' @param src_nodata Set nodata values for input bands.. `1` to `2147483647` value(s)
#' @param dst_nodata Set nodata values at the destination band level.. `1` to `2147483647` value(s)
#' @param hide_nodata Makes the destination band not report the NoData. (Logical)
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples

#' job <- gdal_raster_stack(input = c("red.tif", "green.tif", "blue.tif"), output = "rgb.tif")
#' \dontrun{
#'   result <- gdal_job_run(job)
#' }
#' @export
gdal_raster_stack <- function(input = NULL,
  output,
  output_format = NULL,
  target_aligned_pixels = FALSE,
  creation_option = NULL,
  band = NULL,
  overwrite = FALSE,
  resolution = NULL,
  bbox = NULL,
  src_nodata = NULL,
  dst_nodata = NULL,
  hide_nodata = FALSE) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(target_aligned_pixels)) new_args[["target_aligned_pixels"]] <- target_aligned_pixels
  if (!missing(creation_option)) new_args[["creation_option"]] <- creation_option
  if (!missing(band)) new_args[["band"]] <- band
  if (!missing(overwrite)) new_args[["overwrite"]] <- overwrite
  if (!missing(resolution)) new_args[["resolution"]] <- resolution
  if (!missing(bbox)) new_args[["bbox"]] <- bbox
  if (!missing(src_nodata)) new_args[["src_nodata"]] <- src_nodata
  if (!missing(dst_nodata)) new_args[["dst_nodata"]] <- dst_nodata
  if (!missing(hide_nodata)) new_args[["hide_nodata"]] <- hide_nodata

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("raster", "stack"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    input = list(min_count = 1, max_count = 2147483647),
    output = list(min_count = 0, max_count = 1),
    output_format = list(min_count = 0, max_count = 1),
    target_aligned_pixels = list(min_count = 0, max_count = 1),
    creation_option = list(min_count = 0, max_count = 2147483647),
    band = list(min_count = 0, max_count = 2147483647),
    overwrite = list(min_count = 0, max_count = 1),
    resolution = list(min_count = 0, max_count = 1),
    bbox = list(min_count = 4, max_count = 4),
    src_nodata = list(min_count = 1, max_count = 2147483647),
    dst_nodata = list(min_count = 1, max_count = 2147483647),
    hide_nodata = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("raster", "stack"), arguments = merged_args, arg_mapping = .arg_mapping)
}

