# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.11.4
# Generation date: 2026-04-15
# ===================================================================

#' @title hillshade: Generate a shaded relief map
#' @description
#' Generate a shaded relief map
#' 
#' See \url{https://gdal.org/en/3.11.4/programs/gdal_raster_hillshade.html} for detailed GDAL documentation.
#' @param input Input raster dataset (Dataset path) (required). Can also be a [gdal_job] object to extend a pipeline
#' @param input_format Input formats (Character vector) (Advanced)
#' @param output Output raster dataset (Dataset path) (required)
#' @param output_format Output format ("GDALG" allowed)
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>` (Advanced)
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`
#' @param overwrite Whether overwriting existing output is allowed (Logical) (Default: `false`)
#' @param band Input band (1-based index) (Integer) (Default: `1`)
#' @param zfactor Vertical exaggeration used to pre-multiply the elevations. Minimum: `0`
#' @param xscale Ratio of vertical units to horizontal X axis units. Minimum: `0`
#' @param yscale Ratio of vertical units to horizontal Y axis units. Minimum: `0`
#' @param azimuth Azimuth of the light, in degrees (Default: `315`)
#' @param altitude Altitude of the light, in degrees (Default: `45`). Range: (`0` to `90`)
#' @param gradient_alg Algorithm used to compute terrain gradient. Choices: "Horn", "ZevenbergenThorne" (Default: `Horn`)
#' @param variant Variant of the hillshading algorithm. Choices: "regular", "combined", "multidirectional", "Igor" (Default: `regular`)
#' @param no_edges Do not try to interpolate values at dataset edges or close to nodata values (Logical)
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples

#' job <- gdal_raster_hillshade(input = "n43.dt0", output = "out.tif", overwrite = TRUE, 
#'     zfactor = 30)
#' \dontrun{
#'   result <- gdal_job_run(job)
#' }
#' @export
gdal_raster_hillshade <- function(input,
  input_format = NULL,
  output,
  output_format = NULL,
  open_option = NULL,
  creation_option = NULL,
  overwrite = FALSE,
  band = NULL,
  zfactor = NULL,
  xscale = NULL,
  yscale = NULL,
  azimuth = NULL,
  altitude = NULL,
  gradient_alg = NULL,
  variant = NULL,
  no_edges = FALSE) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(input_format)) new_args[["input_format"]] <- input_format
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(creation_option)) new_args[["creation_option"]] <- creation_option
  if (!missing(overwrite)) new_args[["overwrite"]] <- overwrite
  if (!missing(band)) new_args[["band"]] <- band
  if (!missing(zfactor)) new_args[["zfactor"]] <- zfactor
  if (!missing(xscale)) new_args[["xscale"]] <- xscale
  if (!missing(yscale)) new_args[["yscale"]] <- yscale
  if (!missing(azimuth)) new_args[["azimuth"]] <- azimuth
  if (!missing(altitude)) new_args[["altitude"]] <- altitude
  if (!missing(gradient_alg)) new_args[["gradient_alg"]] <- gradient_alg
  if (!missing(variant)) new_args[["variant"]] <- variant
  if (!missing(no_edges)) new_args[["no_edges"]] <- no_edges

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("raster", "hillshade"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    input = list(min_count = 0, max_count = 1),
    input_format = list(min_count = 0, max_count = 2147483647),
    output = list(min_count = 0, max_count = 1),
    output_format = list(min_count = 0, max_count = 1),
    open_option = list(min_count = 0, max_count = 2147483647),
    creation_option = list(min_count = 0, max_count = 2147483647),
    overwrite = list(min_count = 0, max_count = 1),
    band = list(min_count = 0, max_count = 1),
    zfactor = list(min_count = 0, max_count = 1),
    xscale = list(min_count = 0, max_count = 1),
    yscale = list(min_count = 0, max_count = 1),
    azimuth = list(min_count = 0, max_count = 1),
    altitude = list(min_count = 0, max_count = 1),
    gradient_alg = list(min_count = 0, max_count = 1),
    variant = list(min_count = 0, max_count = 1),
    no_edges = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("raster", "hillshade"), arguments = merged_args, arg_mapping = .arg_mapping)
}

