# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.11.4
# Generation date: 2026-04-15
# ===================================================================

#' @title clip: Clip a raster dataset
#' @description
#' Clip a raster dataset.
#' 
#' See \url{https://gdal.org/en/3.11.4/programs/gdal_raster_clip.html} for detailed GDAL documentation.
#' @param input Input raster dataset (Dataset path) (required). Can also be a [gdal_job] object to extend a pipeline
#' @param input_format Input formats (Character vector) (Advanced)
#' @param output Output raster dataset (Dataset path) (required)
#' @param output_format Output format ("GDALG" allowed)
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>` (Advanced)
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`
#' @param overwrite Whether overwriting existing output is allowed (Logical) (Default: `false`)
#' @param bbox Clipping bounding box as xmin,ymin,xmax,ymax. Exactly `4` value(s)
#' @param bbox_crs CRS of clipping bounding box
#' @param geometry Clipping geometry (WKT or GeoJSON)
#' @param geometry_crs CRS of clipping geometry
#' @param like Dataset to use as a template for bounds (Dataset path). Format: `DATASET`
#' @param like_sql SELECT statement to run on the 'like' dataset. Format: `SELECT-STATEMENT`
#' @param like_layer Name of the layer of the 'like' dataset. Format: `LAYER-NAME`
#' @param like_where WHERE SQL clause to run on the 'like' dataset. Format: `WHERE-EXPRESSION`
#' @param only_bbox For 'geometry' and 'like', only consider their bounding box (Logical)
#' @param allow_bbox_outside_source Allow clipping box to include pixels outside input dataset (Logical)
#' @param add_alpha Adds an alpha mask band to the destination when the source raster have none. (Logical)
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples

#' job <- gdal_raster_clip(input = "in.tif", output = "out.tif", overwrite = TRUE, 
#'     bbox = c(2, 49, 3, 50), bbox_crs = "EPSG:4326")
#' \dontrun{
#'   result <- gdal_job_run(job)
#' }
#' @export
gdal_raster_clip <- function(input,
  input_format = NULL,
  output,
  output_format = NULL,
  open_option = NULL,
  creation_option = NULL,
  overwrite = FALSE,
  bbox = NULL,
  bbox_crs = NULL,
  geometry = NULL,
  geometry_crs = NULL,
  like = NULL,
  like_sql = NULL,
  like_layer = NULL,
  like_where = NULL,
  only_bbox = FALSE,
  allow_bbox_outside_source = FALSE,
  add_alpha = FALSE) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(input_format)) new_args[["input_format"]] <- input_format
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(creation_option)) new_args[["creation_option"]] <- creation_option
  if (!missing(overwrite)) new_args[["overwrite"]] <- overwrite
  if (!missing(bbox)) new_args[["bbox"]] <- bbox
  if (!missing(bbox_crs)) new_args[["bbox_crs"]] <- bbox_crs
  if (!missing(geometry)) new_args[["geometry"]] <- geometry
  if (!missing(geometry_crs)) new_args[["geometry_crs"]] <- geometry_crs
  if (!missing(like)) new_args[["like"]] <- like
  if (!missing(like_sql)) new_args[["like_sql"]] <- like_sql
  if (!missing(like_layer)) new_args[["like_layer"]] <- like_layer
  if (!missing(like_where)) new_args[["like_where"]] <- like_where
  if (!missing(only_bbox)) new_args[["only_bbox"]] <- only_bbox
  if (!missing(allow_bbox_outside_source)) new_args[["allow_bbox_outside_source"]] <- allow_bbox_outside_source
  if (!missing(add_alpha)) new_args[["add_alpha"]] <- add_alpha

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("raster", "clip"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    input = list(min_count = 0, max_count = 1),
    input_format = list(min_count = 0, max_count = 2147483647),
    output = list(min_count = 0, max_count = 1),
    output_format = list(min_count = 0, max_count = 1),
    open_option = list(min_count = 0, max_count = 2147483647),
    creation_option = list(min_count = 0, max_count = 2147483647),
    overwrite = list(min_count = 0, max_count = 1),
    bbox = list(min_count = 4, max_count = 4),
    bbox_crs = list(min_count = 0, max_count = 1),
    geometry = list(min_count = 0, max_count = 1),
    geometry_crs = list(min_count = 0, max_count = 1),
    like = list(min_count = 0, max_count = 1),
    like_sql = list(min_count = 0, max_count = 1),
    like_layer = list(min_count = 0, max_count = 1),
    like_where = list(min_count = 0, max_count = 1),
    only_bbox = list(min_count = 0, max_count = 1),
    allow_bbox_outside_source = list(min_count = 0, max_count = 1),
    add_alpha = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("raster", "clip"), arguments = merged_args, arg_mapping = .arg_mapping)
}

