# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.11.4
# Generation date: 2026-04-24
# ===================================================================

#' @title scale: Scale the values of the bands of a raster dataset
#' @description
#' `gdal raster scale` can be used to rescale the input pixels values from the range --src-min to --src-max to the range --dst-min to --dst-max. It is also often necessary to reset the output datatype with the --ot switch. If omitted the output range is from the minimum value to the maximum value allowed for integer data types (for example from 0 to 255 for Byte output) or from 0 to 1 for floating-point data types. If omitted the input range is automatically computed from the source dataset. This may be a slow operation on a large source dataset, and if using it multiple times for several gdal_translate invocation, it might be beneficial to call ``gdal raster edit --stats \{source_dataset\}`` priorly to precompute statistics, for formats that support serializing statistics computations (GeoTIFF, VRT...) Source values are clipped to the range defined by ``srcmin`` and ``srcmax``, unless --no-clip is set. By default, the scaling is applied to all bands. It is possible to restrict it to a single band with --band and leave values of other bands unmodified. This command is the reverse operation of gdal_raster_unscale. This subcommand is also available as a potential step of gdal_raster_pipeline
#' 
#' See \url{https://gdal.org/en/release-3.11/programs/gdal_raster_scale.html} for detailed GDAL documentation.
#' @param input Input raster dataset (Dataset path) (required). Can also be a [gdal_job] object to extend a pipeline
#' @param input_format Input formats (Character vector) (Advanced)
#' @param output Output raster dataset (Dataset path) (required)
#' @param output_format Output format ("GDALG" allowed)
#' @param output_data_type Output data type. Choices: "Byte", "Int8", "UInt16", "Int16", "UInt32", ...
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>` (Advanced)
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`
#' @param overwrite Whether overwriting existing output is allowed (Logical) (Default: `false`)
#' @param band Select band to restrict the scaling (1-based index) (Integer)
#' @param src_min Minimum value of the source range
#' @param src_max Maximum value of the source range
#' @param dst_min Minimum value of the destination range
#' @param dst_max Maximum value of the destination range
#' @param exponent Exponent to apply non-linear scaling with a power function
#' @param no_clip Do not clip input values to \[srcmin, srcmax\] (Logical)
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples

#' job <- gdal_raster_scale(input = "uint16.tif", output = "byte.tif", overwrite = TRUE, 
#'     src_min = 0, src_max = 4095)
#' \dontrun{
#'   result <- gdal_job_run(job)
#' }
#' @export
gdal_raster_scale <- function(input,
  input_format = NULL,
  output,
  output_format = NULL,
  output_data_type = NULL,
  open_option = NULL,
  creation_option = NULL,
  overwrite = FALSE,
  band = NULL,
  src_min = NULL,
  src_max = NULL,
  dst_min = NULL,
  dst_max = NULL,
  exponent = NULL,
  no_clip = FALSE) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(input_format)) new_args[["input_format"]] <- input_format
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(output_data_type)) new_args[["output_data_type"]] <- output_data_type
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(creation_option)) new_args[["creation_option"]] <- creation_option
  if (!missing(overwrite)) new_args[["overwrite"]] <- overwrite
  if (!missing(band)) new_args[["band"]] <- band
  if (!missing(src_min)) new_args[["src_min"]] <- src_min
  if (!missing(src_max)) new_args[["src_max"]] <- src_max
  if (!missing(dst_min)) new_args[["dst_min"]] <- dst_min
  if (!missing(dst_max)) new_args[["dst_max"]] <- dst_max
  if (!missing(exponent)) new_args[["exponent"]] <- exponent
  if (!missing(no_clip)) new_args[["no_clip"]] <- no_clip

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("raster", "scale"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    input = list(min_count = 0, max_count = 1),
    input_format = list(min_count = 0, max_count = 2147483647),
    output = list(min_count = 0, max_count = 1),
    output_format = list(min_count = 0, max_count = 1),
    output_data_type = list(min_count = 0, max_count = 1),
    open_option = list(min_count = 0, max_count = 2147483647),
    creation_option = list(min_count = 0, max_count = 2147483647),
    overwrite = list(min_count = 0, max_count = 1),
    band = list(min_count = 0, max_count = 1),
    src_min = list(min_count = 0, max_count = 1),
    src_max = list(min_count = 0, max_count = 1),
    dst_min = list(min_count = 0, max_count = 1),
    dst_max = list(min_count = 0, max_count = 1),
    exponent = list(min_count = 0, max_count = 1),
    no_clip = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("raster", "scale"), arguments = merged_args, arg_mapping = .arg_mapping)
}

