# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.11.4
# Generation date: 2026-04-24
# ===================================================================

#' @title list: List files of one of the GDAL Virtual System Interface (VSI)
#' @description
#' `gdal vsi list` list files of virtual_file_systems. This is the equivalent of the UNIX ``ls`` command, and ``gdal vsi ls`` is an alias for ``gdal vsi list``. By default, it outputs file names, at the immediate level, without details, and in JSON format.
#' 
#' See \url{https://gdal.org/en/release-3.11/programs/gdal_vsi_list.html} for detailed GDAL documentation.
#' @param filename File or directory name (required). Can also be a [gdal_job] object to extend a pipeline
#' @param output_format Output format. Choices: "json", "text" (Default: `json`)
#' @param long_listing Use a long listing format (Logical)
#' @param recursive List subdirectories recursively (Logical)
#' @param depth Maximum depth in recursive mode (Integer). Minimum: `1`
#' @param absolute_path Display absolute path (Logical)
#' @param tree Use a hierarchical presentation for JSON output (Logical)
#' @param stdout Directly output on stdout. If enabled, output-string will be empty (Logical)
#' @return A [gdal_job] object.
#' @family gdal_vsi_utilities
#' @examples
#' \dontrun{
#' # TODO: No examples available for gdal_vsi_list.
#' # See GDAL documentation: https://gdal.org/programs/gdal-vsi-list.html
#' job <- gdal_vsi_list()
#' # gdal_job_run(job)
#' }
#' @export
gdal_vsi_list <- function(filename,
  output_format = NULL,
  long_listing = FALSE,
  recursive = FALSE,
  depth = NULL,
  absolute_path = FALSE,
  tree = FALSE,
  stdout = FALSE) {
  new_args <- list()
  if (!missing(filename)) new_args[["filename"]] <- filename
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(long_listing)) new_args[["long_listing"]] <- long_listing
  if (!missing(recursive)) new_args[["recursive"]] <- recursive
  if (!missing(depth)) new_args[["depth"]] <- depth
  if (!missing(absolute_path)) new_args[["absolute_path"]] <- absolute_path
  if (!missing(tree)) new_args[["tree"]] <- tree
  if (!missing(stdout)) new_args[["stdout"]] <- stdout

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(filename) && inherits(filename, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- filename
    new_args[["filename"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("vsi", "list"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    filename = list(min_count = 0, max_count = 1),
    output_format = list(min_count = 0, max_count = 1),
    long_listing = list(min_count = 0, max_count = 1),
    recursive = list(min_count = 0, max_count = 1),
    depth = list(min_count = 0, max_count = 1),
    absolute_path = list(min_count = 0, max_count = 1),
    tree = list(min_count = 0, max_count = 1),
    stdout = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("vsi", "list"), arguments = merged_args, arg_mapping = .arg_mapping)
}

