# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.11.4
# Generation date: 2026-04-24
# ===================================================================

#' @title fill-nodata: Fill nodata raster regions by interpolation from edges
#' @description
#' `gdal raster fill-nodata` fills nodata areas by interpolating from valid pixels around the edges of the area. This subcommand is also available as a potential step of gdal_raster_pipeline (since GDAL 3.12)
#' 
#' See \url{https://gdal.org/en/release-3.11/programs/gdal_raster_fill-nodata.html} for detailed GDAL documentation.
#' @param input Input raster dataset (Dataset path) (required). Can also be a [gdal_job] object to extend a pipeline
#' @param input_format Input formats (Character vector) (Advanced)
#' @param output Output raster dataset (Dataset path) (required)
#' @param output_format Output format
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`
#' @param overwrite Whether overwriting existing output is allowed (Logical) (Default: `false`)
#' @param band Input band (1-based index) (Integer) (Default: `1`)
#' @param max_distance The maximum distance (in pixels) that the algorithm will search out for values to interpolate. (Integer). Format: `MAX_DISTANCE` (Default: `100`)
#' @param smoothing_iterations The number of 3x3 average filter smoothing iterations to run after the interpolation to dampen artifacts. The default is zero smoothing iterations. (Integer). Format: `SMOOTHING_ITERATIONS` (Default: `0`)
#' @param mask Use the first band of the specified file as a validity mask (zero is invalid, non-zero is valid). (Dataset path)
#' @param strategy By default, pixels are interpolated using an inverse distance weighting (invdist). It is also possible to choose a nearest neighbour (nearest) strategy.. Choices: "invdist", "nearest" (Default: `invdist`)
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples

#' job <- gdal_raster_fill_nodata(input = "input.tif", output = "output.tif", 
#'     max_distance = 50, smoothing_iterations = 3, strategy = "nearest", mask = "mask.tif")
#' \dontrun{
#'   result <- gdal_job_run(job)
#' }
#' @export
gdal_raster_fill_nodata <- function(input,
  input_format = NULL,
  output,
  output_format = NULL,
  creation_option = NULL,
  overwrite = FALSE,
  band = NULL,
  max_distance = NULL,
  smoothing_iterations = NULL,
  mask = NULL,
  strategy = NULL) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(input_format)) new_args[["input_format"]] <- input_format
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(creation_option)) new_args[["creation_option"]] <- creation_option
  if (!missing(overwrite)) new_args[["overwrite"]] <- overwrite
  if (!missing(band)) new_args[["band"]] <- band
  if (!missing(max_distance)) new_args[["max_distance"]] <- max_distance
  if (!missing(smoothing_iterations)) new_args[["smoothing_iterations"]] <- smoothing_iterations
  if (!missing(mask)) new_args[["mask"]] <- mask
  if (!missing(strategy)) new_args[["strategy"]] <- strategy

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("raster", "fill-nodata"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    input = list(min_count = 0, max_count = 1),
    input_format = list(min_count = 0, max_count = 2147483647),
    output = list(min_count = 0, max_count = 1),
    output_format = list(min_count = 0, max_count = 1),
    creation_option = list(min_count = 0, max_count = 2147483647),
    overwrite = list(min_count = 0, max_count = 1),
    band = list(min_count = 0, max_count = 1),
    max_distance = list(min_count = 0, max_count = 1),
    smoothing_iterations = list(min_count = 0, max_count = 1),
    mask = list(min_count = 0, max_count = 1),
    strategy = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("raster", "fill-nodata"), arguments = merged_args, arg_mapping = .arg_mapping)
}

