# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.11.4
# Generation date: 2026-04-24
# ===================================================================

#' @title create: Create a new raster dataset
#' @description
#' `gdal raster create` can be used to initialize a new raster file, from its dimensions, band count, CRS, geotransform, nodata value and metadata. The new file can also be initialized from a model input file with the optional --like option, copying its properties but not its pixel values. By default, metadata and the overview structure are not copied from the model input file, unless --copy-metadata and --copy-overviews are specified. Options --size, --band-count, --datatype, --nodata, --crs, --bbox, --metadata can be used to override the values inherited from the model input file. For GeoTIFF output, setting the ``SPARSE_OK`` creation option to ``YES`` can be useful to create a file of minimum size.` gdal raster create can be used also in special cases, like creating a PDF file from a XML composition file.
#' 
#' See \url{https://gdal.org/en/release-3.11/programs/gdal_raster_create.html} for detailed GDAL documentation.
#' @param input Input raster dataset (Dataset path). Can also be a [gdal_job] object to extend a pipeline
#' @param input_format Input formats (Character vector) (Advanced)
#' @param output Output raster dataset (Dataset path) (required)
#' @param output_format Output format
#' @param output_data_type Output data type. Choices: "Byte", "Int8", "UInt16", "Int16", "UInt32", ... (Default: `Byte`)
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>` (Advanced)
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`
#' @param overwrite Whether overwriting existing output is allowed (Logical) (Default: `false`)
#' @param append Append as a subdataset to existing output (Logical) (Default: `false`)
#' @param size Output size in pixels (Integer vector). Format: `<width>,<height>`. Minimum: `0`. Exactly `2` value(s)
#' @param band_count Number of bands (Integer) (Default: `1`). Minimum: `0`
#' @param nodata Assign a specified nodata value to output bands ('none', numeric value, 'nan', 'inf', '-inf')
#' @param burn Burn value
#' @param crs Set CRS
#' @param bbox Bounding box as xmin,ymin,xmax,ymax. Exactly `4` value(s)
#' @param metadata Add metadata item (Character vector). Format: `<KEY>=<VALUE>`
#' @param copy_metadata Copy metadata from input dataset (Logical)
#' @param copy_overviews Create same overview levels as input dataset (Logical)
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples

#' job <- gdal_raster_create(input = "out.tif", size = c(20, 20), band_count = 3, 
#'     crs = "EPSG:4326", bbox = c(2, 49, 3, 50), burn = 10)
#' \dontrun{
#'   result <- gdal_job_run(job)
#' }
#' @export
gdal_raster_create <- function(input = NULL,
  input_format = NULL,
  output,
  output_format = NULL,
  output_data_type = NULL,
  open_option = NULL,
  creation_option = NULL,
  overwrite = FALSE,
  append = FALSE,
  size = NULL,
  band_count = NULL,
  nodata = NULL,
  burn = NULL,
  crs = NULL,
  bbox = NULL,
  metadata = NULL,
  copy_metadata = FALSE,
  copy_overviews = FALSE) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(input_format)) new_args[["input_format"]] <- input_format
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(output_data_type)) new_args[["output_data_type"]] <- output_data_type
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(creation_option)) new_args[["creation_option"]] <- creation_option
  if (!missing(overwrite)) new_args[["overwrite"]] <- overwrite
  if (!missing(append)) new_args[["append"]] <- append
  if (!missing(size)) new_args[["size"]] <- size
  if (!missing(band_count)) new_args[["band_count"]] <- band_count
  if (!missing(nodata)) new_args[["nodata"]] <- nodata
  if (!missing(burn)) new_args[["burn"]] <- burn
  if (!missing(crs)) new_args[["crs"]] <- crs
  if (!missing(bbox)) new_args[["bbox"]] <- bbox
  if (!missing(metadata)) new_args[["metadata"]] <- metadata
  if (!missing(copy_metadata)) new_args[["copy_metadata"]] <- copy_metadata
  if (!missing(copy_overviews)) new_args[["copy_overviews"]] <- copy_overviews

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("raster", "create"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    input = list(min_count = 0, max_count = 1),
    input_format = list(min_count = 0, max_count = 2147483647),
    output = list(min_count = 0, max_count = 1),
    output_format = list(min_count = 0, max_count = 1),
    output_data_type = list(min_count = 0, max_count = 1),
    open_option = list(min_count = 0, max_count = 2147483647),
    creation_option = list(min_count = 0, max_count = 2147483647),
    overwrite = list(min_count = 0, max_count = 1),
    append = list(min_count = 0, max_count = 1),
    size = list(min_count = 2, max_count = 2),
    band_count = list(min_count = 0, max_count = 1),
    nodata = list(min_count = 0, max_count = 1),
    burn = list(min_count = 0, max_count = 2147483647),
    crs = list(min_count = 0, max_count = 1),
    bbox = list(min_count = 4, max_count = 4),
    metadata = list(min_count = 0, max_count = 2147483647),
    copy_metadata = list(min_count = 0, max_count = 1),
    copy_overviews = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("raster", "create"), arguments = merged_args, arg_mapping = .arg_mapping)
}

