# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.11.4
# Generation date: 2026-04-15
# ===================================================================

#' @title set-type: Modify the geometry type of a vector dataset
#' @description
#' Modify the geometry type of a vector dataset.
#' 
#' See \url{https://gdal.org/en/3.11.4/programs/gdal_vector_geom_set-type.html} for detailed GDAL documentation.
#' @param input Input vector datasets (required). Exactly `1` value(s). Can also be a [gdal_job] object to extend a pipeline
#' @param input_format Input formats (Character vector) (Advanced)
#' @param input_layer Input layer name(s) (Character vector)
#' @param output Output vector dataset (Dataset path) (required)
#' @param output_format Output format ("GDALG" allowed)
#' @param output_layer Output layer name
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>` (Advanced)
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`
#' @param layer_creation_option Layer creation option (Character vector). Format: `<KEY>=<VALUE>`
#' @param overwrite Whether overwriting existing output is allowed (Logical) (Default: `false`)
#' @param update Whether to open existing dataset in update mode (Logical) (Default: `false`)
#' @param overwrite_layer Whether overwriting existing layer is allowed (Logical) (Default: `false`)
#' @param append Whether appending to existing layer is allowed (Logical) (Default: `false`)
#' @param active_layer Set active layer (if not specified, all)
#' @param active_geometry Geometry field name to which to restrict the processing (if not specified, all)
#' @param layer_only Only modify the layer geometry type (Logical)
#' @param feature_only Only modify the geometry type of features (Logical)
#' @param geometry_type Geometry type
#' @param multi Force geometries to MULTI geometry types (Logical)
#' @param single Force geometries to non-MULTI geometry types (Logical)
#' @param linear Convert curve geometries to linear types (Logical)
#' @param curve Convert linear geometries to curve types (Logical)
#' @param dim Force geometries to the specified dimension. Choices: "XY", "XYZ", "XYM", "XYZM"
#' @param skip Skip feature when change of feature geometry type failed (Logical)
#' @return A [gdal_job] object.
#' @family gdal_vector_utilities
#' @examples

#' job <- gdal_vector_geom_set_type(input = "in.shp", output = "out.gpkg", overwrite = TRUE, 
#'     geometry_type = "MULTIPOLYGON")
#' \dontrun{
#'   result <- gdal_job_run(job)
#' }
#' @export
gdal_vector_geom_set_type <- function(input,
  input_format = NULL,
  input_layer = NULL,
  output,
  output_format = NULL,
  output_layer = NULL,
  open_option = NULL,
  creation_option = NULL,
  layer_creation_option = NULL,
  overwrite = FALSE,
  update = FALSE,
  overwrite_layer = FALSE,
  append = FALSE,
  active_layer = NULL,
  active_geometry = NULL,
  layer_only = FALSE,
  feature_only = FALSE,
  geometry_type = NULL,
  multi = FALSE,
  single = FALSE,
  linear = FALSE,
  curve = FALSE,
  dim = NULL,
  skip = FALSE) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(input_format)) new_args[["input_format"]] <- input_format
  if (!missing(input_layer)) new_args[["input_layer"]] <- input_layer
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(output_layer)) new_args[["output_layer"]] <- output_layer
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(creation_option)) new_args[["creation_option"]] <- creation_option
  if (!missing(layer_creation_option)) new_args[["layer_creation_option"]] <- layer_creation_option
  if (!missing(overwrite)) new_args[["overwrite"]] <- overwrite
  if (!missing(update)) new_args[["update"]] <- update
  if (!missing(overwrite_layer)) new_args[["overwrite_layer"]] <- overwrite_layer
  if (!missing(append)) new_args[["append"]] <- append
  if (!missing(active_layer)) new_args[["active_layer"]] <- active_layer
  if (!missing(active_geometry)) new_args[["active_geometry"]] <- active_geometry
  if (!missing(layer_only)) new_args[["layer_only"]] <- layer_only
  if (!missing(feature_only)) new_args[["feature_only"]] <- feature_only
  if (!missing(geometry_type)) new_args[["geometry_type"]] <- geometry_type
  if (!missing(multi)) new_args[["multi"]] <- multi
  if (!missing(single)) new_args[["single"]] <- single
  if (!missing(linear)) new_args[["linear"]] <- linear
  if (!missing(curve)) new_args[["curve"]] <- curve
  if (!missing(dim)) new_args[["dim"]] <- dim
  if (!missing(skip)) new_args[["skip"]] <- skip

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("vector", "geom", "set-type"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    input = list(min_count = 1, max_count = 1),
    input_format = list(min_count = 0, max_count = 2147483647),
    input_layer = list(min_count = 0, max_count = 2147483647),
    output = list(min_count = 0, max_count = 1),
    output_format = list(min_count = 0, max_count = 1),
    output_layer = list(min_count = 0, max_count = 1),
    open_option = list(min_count = 0, max_count = 2147483647),
    creation_option = list(min_count = 0, max_count = 2147483647),
    layer_creation_option = list(min_count = 0, max_count = 2147483647),
    overwrite = list(min_count = 0, max_count = 1),
    update = list(min_count = 0, max_count = 1),
    overwrite_layer = list(min_count = 0, max_count = 1),
    append = list(min_count = 0, max_count = 1),
    active_layer = list(min_count = 0, max_count = 1),
    active_geometry = list(min_count = 0, max_count = 1),
    layer_only = list(min_count = 0, max_count = 1),
    feature_only = list(min_count = 0, max_count = 1),
    geometry_type = list(min_count = 0, max_count = 1),
    multi = list(min_count = 0, max_count = 1),
    single = list(min_count = 0, max_count = 1),
    linear = list(min_count = 0, max_count = 1),
    curve = list(min_count = 0, max_count = 1),
    dim = list(min_count = 0, max_count = 1),
    skip = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("vector", "geom", "set-type"), arguments = merged_args, arg_mapping = .arg_mapping)
}

