# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.11.4
# Generation date: 2026-04-15
# ===================================================================

#' @title reproject: Reproject a raster dataset
#' @description
#' Reproject a raster dataset.
#' 
#' See \url{https://gdal.org/en/3.11.4/programs/gdal_raster_reproject.html} for detailed GDAL documentation.
#' @param input Input raster dataset (Dataset path) (required). Can also be a [gdal_job] object to extend a pipeline
#' @param input_format Input formats (Character vector) (Advanced)
#' @param output Output raster dataset (Dataset path) (required)
#' @param output_format Output format ("GDALG" allowed)
#' @param target_aligned_pixels Round target extent to target resolution (Logical) (Advanced)
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>` (Advanced)
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`
#' @param overwrite Whether overwriting existing output is allowed (Logical) (Default: `false`)
#' @param src_crs Source CRS
#' @param dst_crs Destination CRS
#' @param resampling Resampling method. Choices: "nearest", "bilinear", "cubic", "cubicspline", "lanczos", ... (Default: `nearest`)
#' @param resolution Target resolution (in destination CRS units). Format: `<xres>,<yres>`. Minimum: `0`. Exactly `2` value(s)
#' @param size Target size in pixels (Integer vector). Format: `<width>,<height>`. Minimum: `0`. Exactly `2` value(s)
#' @param bbox Target bounding box (in destination CRS units). Exactly `4` value(s)
#' @param bbox_crs CRS of target bounding box
#' @param src_nodata Set nodata values for input bands ('None' to unset). (Character vector). `1` to `2147483647` value(s) (Advanced)
#' @param dst_nodata Set nodata values for output bands ('None' to unset). (Character vector). `1` to `2147483647` value(s) (Advanced)
#' @param add_alpha Adds an alpha mask band to the destination when the source raster have none. (Logical) (Advanced)
#' @param warp_option Warping option(s) (Character vector). Format: `<NAME>=<VALUE>` (Advanced)
#' @param transform_option Transform option(s) (Character vector). Format: `<NAME>=<VALUE>` (Advanced)
#' @param error_threshold Error threshold (Advanced)
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples

#' job <- gdal_raster_reproject(input = "in.tif", output = "out.tif", overwrite = TRUE, 
#'     dst_crs = "EPSG:32632")
#' \dontrun{
#'   result <- gdal_job_run(job)
#' }
#' @export
gdal_raster_reproject <- function(input,
  input_format = NULL,
  output,
  output_format = NULL,
  target_aligned_pixels = FALSE,
  open_option = NULL,
  creation_option = NULL,
  overwrite = FALSE,
  src_crs = NULL,
  dst_crs = NULL,
  resampling = NULL,
  resolution = NULL,
  size = NULL,
  bbox = NULL,
  bbox_crs = NULL,
  src_nodata = NULL,
  dst_nodata = NULL,
  add_alpha = FALSE,
  warp_option = NULL,
  transform_option = NULL,
  error_threshold = NULL) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(input_format)) new_args[["input_format"]] <- input_format
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(target_aligned_pixels)) new_args[["target_aligned_pixels"]] <- target_aligned_pixels
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(creation_option)) new_args[["creation_option"]] <- creation_option
  if (!missing(overwrite)) new_args[["overwrite"]] <- overwrite
  if (!missing(src_crs)) new_args[["src_crs"]] <- src_crs
  if (!missing(dst_crs)) new_args[["dst_crs"]] <- dst_crs
  if (!missing(resampling)) new_args[["resampling"]] <- resampling
  if (!missing(resolution)) new_args[["resolution"]] <- resolution
  if (!missing(size)) new_args[["size"]] <- size
  if (!missing(bbox)) new_args[["bbox"]] <- bbox
  if (!missing(bbox_crs)) new_args[["bbox_crs"]] <- bbox_crs
  if (!missing(src_nodata)) new_args[["src_nodata"]] <- src_nodata
  if (!missing(dst_nodata)) new_args[["dst_nodata"]] <- dst_nodata
  if (!missing(add_alpha)) new_args[["add_alpha"]] <- add_alpha
  if (!missing(warp_option)) new_args[["warp_option"]] <- warp_option
  if (!missing(transform_option)) new_args[["transform_option"]] <- transform_option
  if (!missing(error_threshold)) new_args[["error_threshold"]] <- error_threshold

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("raster", "reproject"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    input = list(min_count = 0, max_count = 1),
    input_format = list(min_count = 0, max_count = 2147483647),
    output = list(min_count = 0, max_count = 1),
    output_format = list(min_count = 0, max_count = 1),
    target_aligned_pixels = list(min_count = 0, max_count = 1),
    open_option = list(min_count = 0, max_count = 2147483647),
    creation_option = list(min_count = 0, max_count = 2147483647),
    overwrite = list(min_count = 0, max_count = 1),
    src_crs = list(min_count = 0, max_count = 1),
    dst_crs = list(min_count = 0, max_count = 1),
    resampling = list(min_count = 0, max_count = 1),
    resolution = list(min_count = 2, max_count = 2),
    size = list(min_count = 2, max_count = 2),
    bbox = list(min_count = 4, max_count = 4),
    bbox_crs = list(min_count = 0, max_count = 1),
    src_nodata = list(min_count = 1, max_count = 2147483647),
    dst_nodata = list(min_count = 1, max_count = 2147483647),
    add_alpha = list(min_count = 0, max_count = 1),
    warp_option = list(min_count = 0, max_count = 2147483647),
    transform_option = list(min_count = 0, max_count = 2147483647),
    error_threshold = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("raster", "reproject"), arguments = merged_args, arg_mapping = .arg_mapping)
}

