# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.11.4
# Generation date: 2026-04-15
# ===================================================================

#' @title delete: Deleting overviews
#' @description
#' Deleting overviews.
#' 
#' See \url{https://gdal.org/en/3.11.4/programs/gdal_raster_overview_delete.html} for detailed GDAL documentation.
#' @param dataset Dataset (to be updated in-place, unless --read-only) (Dataset path) (required). Can also be a [gdal_job] object to extend a pipeline
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>` (Advanced)
#' @param external Delete external overviews (Logical)
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples

#' job <- gdal_raster_overview_delete(dataset = "my.tif")
#' \dontrun{
#'   result <- gdal_job_run(job)
#' }
#' @export
gdal_raster_overview_delete <- function(dataset,
  open_option = NULL,
  external = FALSE) {
  new_args <- list()
  if (!missing(dataset)) new_args[["dataset"]] <- dataset
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(external)) new_args[["external"]] <- external

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(dataset) && inherits(dataset, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- dataset
    new_args[["dataset"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("raster", "overview", "delete"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    dataset = list(min_count = 0, max_count = 1),
    open_option = list(min_count = 0, max_count = 2147483647),
    external = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("raster", "overview", "delete"), arguments = merged_args, arg_mapping = .arg_mapping)
}

