# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.11.4
# Generation date: 2026-04-15
# ===================================================================

#' @title optimize: Create a Seek-optimized ZIP (SOZIP) file from a regular ZIP file
#' @description
#' Create a Seek-optimized ZIP (SOZIP) file from a regular ZIP file.
#' 
#' See \url{https://gdal.org/en/3.11.4/programs/gdal_vsi_sozip_optimize.html} for detailed GDAL documentation.
#' @param input Input ZIP filename (Character vector) (required). `0` to `1` value(s). Can also be a [gdal_job] object to extend a pipeline
#' @param output Output ZIP filename (required)
#' @param overwrite Whether overwriting existing output is allowed (Logical) (Default: `false`)
#' @param enable_sozip Whether to automatically/systematically/never apply the SOZIP optimization. Choices: "auto", "yes", "no" (Default: `auto`)
#' @param sozip_chunk_size Chunk size for a seek-optimized file. Format: `value in bytes or with K/M suffix` (Default: `32768`)
#' @param sozip_min_file_size Minimum file size to decide if a file should be seek-optimized. Format: `value in bytes or with K/M/G suffix` (Default: `1 MB`)
#' @param stdout Directly output on stdout. If enabled, output-string will be empty (Logical)
#' @return A [gdal_job] object.
#' @family gdal_vsi_utilities
#' @examples

#' job <- gdal_vsi_sozip_optimize(input = "my.gpkg", output = "my.gpkg.zip")
#' \dontrun{
#'   result <- gdal_job_run(job)
#' }
#' @export
gdal_vsi_sozip_optimize <- function(input,
  output,
  overwrite = FALSE,
  enable_sozip = NULL,
  sozip_chunk_size = NULL,
  sozip_min_file_size = NULL,
  stdout = FALSE) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(overwrite)) new_args[["overwrite"]] <- overwrite
  if (!missing(enable_sozip)) new_args[["enable_sozip"]] <- enable_sozip
  if (!missing(sozip_chunk_size)) new_args[["sozip_chunk_size"]] <- sozip_chunk_size
  if (!missing(sozip_min_file_size)) new_args[["sozip_min_file_size"]] <- sozip_min_file_size
  if (!missing(stdout)) new_args[["stdout"]] <- stdout

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("vsi", "sozip", "optimize"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    input = list(min_count = 0, max_count = 1),
    output = list(min_count = 0, max_count = 1),
    overwrite = list(min_count = 0, max_count = 1),
    enable_sozip = list(min_count = 0, max_count = 1),
    sozip_chunk_size = list(min_count = 0, max_count = 1),
    sozip_min_file_size = list(min_count = 0, max_count = 1),
    stdout = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("vsi", "sozip", "optimize"), arguments = merged_args, arg_mapping = .arg_mapping)
}

