# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.11.4
# Generation date: 2026-04-24
# ===================================================================

#' @title concat: Concatenate vector datasets
#' @description
#' `gdal vector concat` concatenates several source datasets. It has 3 main modes: - --mode = ``merge-per-layer-name`` (the default). The output dataset generated by the command will contain as many layers as there are different layer names in the source datasets. For example if there are 2 datasets, one with layers `a` and `b`, and the other one with layers `b` and `c`, 3 output layers will be created: `a`, `b` (merging the 2 source layers) and `c`. - --mode = ``stack``. The output dataset generated by the command will contain as many layers as there are layers in the source datasets. For example if there are 2 datasets ``ds1`` (with layers `a` and `b`) and ``ds2`` (with layers `b` and `c`), 4 output layers will be created: ``ds1_a``, ``ds1_b``, ``ds2_b`` and ``ds2_c``. - --mode = ``single``. The output dataset generated by the command will contain one single layer, merging all layers in the source datasets. When an output layer merges several source layer, by default the resulting schema will contain the union of all source fields. It is possible to select only the intersection with the --field-strategy set to ``intersection``. Regarding the resulting CRS, by default the CRS of the source layer will be used as the target CRS, and features of other source layers that do no match this CRS will be reprojected to it. --dst-crs can be used to select a given destination CRS. This command can also be used as the first step of gdal_vector_pipeline.
#' 
#' See \url{https://gdal.org/en/release-3.11/programs/gdal_vector_concat.html} for detailed GDAL documentation.
#' @param input Input vector datasets (required). `1` to `2147483647` value(s). Can also be a [gdal_job] object to extend a pipeline
#' @param input_format Input formats (Character vector) (Advanced)
#' @param input_layer Input layer name(s) (Character vector)
#' @param source_layer_field_name Name of the new field to add to contain identificoncation of the source layer, with value determined from 'source-layer-field-content'
#' @param source_layer_field_content A string, possibly using \{AUTO_NAME\}, \{DS_NAME\}, \{DS_BASENAME\}, \{DS_INDEX\}, \{LAYER_NAME\}, \{LAYER_INDEX\}
#' @param output Output vector dataset (Dataset path) (required)
#' @param output_format Output format ("GDALG" allowed)
#' @param output_layer Name of the output vector layer (single mode), or template to name the output vector layers (stack mode)
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>` (Advanced)
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`
#' @param layer_creation_option Layer creation option (Character vector). Format: `<KEY>=<VALUE>`
#' @param overwrite Whether overwriting existing output is allowed (Logical) (Default: `false`)
#' @param update Whether to open existing dataset in update mode (Logical) (Default: `false`)
#' @param overwrite_layer Whether overwriting existing layer is allowed (Logical) (Default: `false`)
#' @param append Whether appending to existing layer is allowed (Logical) (Default: `false`)
#' @param mode Determine the strategy to create output layers from source layers . Choices: "merge-per-layer-name", "stack", "single" (Default: `merge-per-layer-name`)
#' @param field_strategy How to determine target fields from source fields. Choices: "union", "intersection" (Default: `union`)
#' @param src_crs Source CRS
#' @param dst_crs Destination CRS
#' @return A [gdal_job] object.
#' @family gdal_vector_utilities
#' @examples

#' job <- gdal_vector_concat(input = "*.shp", output = "out.gpkg", mode = "stack")
#' \dontrun{
#'   result <- gdal_job_run(job)
#' }
#' @export
gdal_vector_concat <- function(input,
  input_format = NULL,
  input_layer = NULL,
  source_layer_field_name = NULL,
  source_layer_field_content = NULL,
  output,
  output_format = NULL,
  output_layer = NULL,
  open_option = NULL,
  creation_option = NULL,
  layer_creation_option = NULL,
  overwrite = FALSE,
  update = FALSE,
  overwrite_layer = FALSE,
  append = FALSE,
  mode = NULL,
  field_strategy = NULL,
  src_crs = NULL,
  dst_crs = NULL) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(input_format)) new_args[["input_format"]] <- input_format
  if (!missing(input_layer)) new_args[["input_layer"]] <- input_layer
  if (!missing(source_layer_field_name)) new_args[["source_layer_field_name"]] <- source_layer_field_name
  if (!missing(source_layer_field_content)) new_args[["source_layer_field_content"]] <- source_layer_field_content
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(output_layer)) new_args[["output_layer"]] <- output_layer
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(creation_option)) new_args[["creation_option"]] <- creation_option
  if (!missing(layer_creation_option)) new_args[["layer_creation_option"]] <- layer_creation_option
  if (!missing(overwrite)) new_args[["overwrite"]] <- overwrite
  if (!missing(update)) new_args[["update"]] <- update
  if (!missing(overwrite_layer)) new_args[["overwrite_layer"]] <- overwrite_layer
  if (!missing(append)) new_args[["append"]] <- append
  if (!missing(mode)) new_args[["mode"]] <- mode
  if (!missing(field_strategy)) new_args[["field_strategy"]] <- field_strategy
  if (!missing(src_crs)) new_args[["src_crs"]] <- src_crs
  if (!missing(dst_crs)) new_args[["dst_crs"]] <- dst_crs

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("vector", "concat"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    input = list(min_count = 1, max_count = 2147483647),
    input_format = list(min_count = 0, max_count = 2147483647),
    input_layer = list(min_count = 0, max_count = 2147483647),
    source_layer_field_name = list(min_count = 0, max_count = 1),
    source_layer_field_content = list(min_count = 0, max_count = 1),
    output = list(min_count = 0, max_count = 1),
    output_format = list(min_count = 0, max_count = 1),
    output_layer = list(min_count = 0, max_count = 1),
    open_option = list(min_count = 0, max_count = 2147483647),
    creation_option = list(min_count = 0, max_count = 2147483647),
    layer_creation_option = list(min_count = 0, max_count = 2147483647),
    overwrite = list(min_count = 0, max_count = 1),
    update = list(min_count = 0, max_count = 1),
    overwrite_layer = list(min_count = 0, max_count = 1),
    append = list(min_count = 0, max_count = 1),
    mode = list(min_count = 0, max_count = 1),
    field_strategy = list(min_count = 0, max_count = 1),
    src_crs = list(min_count = 0, max_count = 1),
    dst_crs = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("vector", "concat"), arguments = merged_args, arg_mapping = .arg_mapping)
}

